### ISSUE TITLE
Expose sel()

### ISSUE THREAD

**Issue by jaredpalmer** [kentcdodds/react-testing-library#1]
React Native Web's `testID` prop emits `data-testid` instead of `data-test`. Would be great if this could be set. Seems like you've already thought about it.

Awesome lib Kent!

**Comment by kentcdodds** [comment]
Hi @jaredpalmer! Yeah, that'd be fine with me! Feel free to make a PR to allow that to be configurable :+1:

**Comment by kentcdodds** [comment]
Actually, I'm thinking of changing this to the default. Want to open a PR?

**Comment by jaredpalmer** [comment]
I’m out of office right today. Womp womp

**Comment by kentcdodds** [comment]
I'll go ahead and do it right now :+1:

**Comment by kentcdodds** [comment]
I'm going to go ahead and assume nobody's used the lib yet so I'll push this as a patch release :)

**Comment by kentcdodds** [comment]
Published 1.0.1

I also updated [my blog post about these attributes](https://blog.kentcdodds.com/making-your-ui-tests-resilient-to-change-d37a6ee37269) so it's consistant.

**Comment by dnlsandiego** [comment]
How about expanding the name `sel` to `select`? Was reading through the source and found the name confusing at first glance. Only after reading your blog post did I find out what it was short for. I mean it's only going to be 3 characters more 😄.

If you agree, I'd be glad to submit a PR for it.

(Really lovin this library btw. Finally found a testing library with a philosophy I agree and am comfortable with)

**Comment by kentcdodds** [comment]
That'd be fine with me :+1: It's an internal function anyway so I don't mind renaming it to be more clear. Definitely wont be a breaking change :+1:

**Comment by kentcdodds** [comment]
And by that I mean, yes, I'd love a PR!
