### ISSUE TITLE
Typo in TextMatch example

### ISSUE THREAD

**Issue by sotobuild** [kentcdodds/react-testing-library#101]
In the second `getByText` example of [TextMatch](https://github.com/kentcdodds/react-testing-library#textmatch), the closing parentesis should be at the end of the statement:

`getByText(container, 'llo Worl', {exact: false})` instead of 

`getByText(container, 'llo Worl'), {exact: false}`

**Comment by kentcdodds** [comment]
Thanks for the catch! Would you like to [make a pull request](http://makeapullrequest.com) to fix it?

**Comment by sotobuild** [comment]
Sure! I'll do that :)
