### ISSUE TITLE
Object.entries is not a function when importing react-testing-library

### ISSUE THREAD

**Issue by snekse** [kentcdodds/react-testing-library#110]
Reporting this as an issue along with the fix in hopes that it helps others find the answer quicker.

**Problem**
When importing `react-testing-library` and running my tests, they failed with the following error

> ```Object.entries is not a function```

**Version Information**
* `react-testing-library` version: 3.1.4
* `react` version: N/A
* `node` version: 6.x
* `npm` (or `yarn`) version: 6.x

**Solution**

Per @kentcdodds [suggestion](https://github.com/paypal/glamorous/issues/302#issuecomment-355301156) in a glamorous ticket:

> Make sure you're on the latest stable node (>=8) and npm (>= 5). Sorry about that!

Upgrading to the latest version of node did indeed resolve my issue.

**Comment by gnapse** [comment]
I guess it wouldn't harm to use `Object.keys` instead. I think is supported in more environments than `Object.entries`, and can be used to achieve the same goals.

**Comment by snekse** [comment]
To be clear, I'm not using `Object.keys` or `Object.entries` in my testing code.  Simply adding `import * as rtlib from 'react-testing-library'` causes this.  I'm assuming it's because the library is using these features.  In my mind it's not a big deal to update node which I should have done a long time ago.

**Comment by gnapse** [comment]
Yes I know. What I suggested was regarding the code in this library, that maybe that code could with to use `Object.keys`, which I believe is more widely supported.

**Comment by kentcdodds** [comment]
Considering Node 6 is on [maintenance LTS](https://github.com/nodejs/Release#release-schedule), I don't care to support it anymore. We should update our engines config in package.json.

**Comment by muyaszed** [comment]
Hi guys, sorry if i'm not doing this right. I happen to encounter this problem again. All my node, npm and react-testing-library is all up to date. The solution I am using right now is importing babel-polyfill

**Comment by kentcdodds** [comment]
Hmmmm.... Could you create a simple reproduction repository?

**Comment by muyaszed** [comment]
Amazingly now I can't replicate the error even after totally removing the babel-polyfil, ahhaha. Can't really say anything much right now, just sorry for the noise. Most probably it is because I accidentally installed jest-cli over CRA but then later I decide to remove, install and update everything. Cheers

**Comment by nitish24p** [comment]
Hi @kentcdodds I'm getting this issue
<img width="674" alt="screen shot 2018-10-09 at 1 51 47 am" src="https://user-images.githubusercontent.com/13037986/46631788-14bf8a80-cb66-11e8-9548-2466707e8d2c.png">
```javascript


import React from 'react';
import { render, cleanup, fireEvent } from 'react-testing-library';
import Button from '../';

afterEach(cleanup);

test('renders the button component', () => {
  const { container } = render(<Button>CLICK ME</Button>);
  expect(container).toMatchSnapshot();
});

test('Handle Click', () => {
  const handleClick = jest.fn();
  const { getByText } = render(<Button onClick={handleClick}>SUBMIT</Button>);
  fireEvent.click(getByText('SUBMIT'));
  expect(handleClick).toHaveBeenCalledTimes(1);
});

```

I am running these tests as part of a precommit hook. My package.json is as shown
```json
{
  ... Other things
   "scripts": {
    "test": "node scripts/custom-config test --env=jsdom",
    "test:staged": "cross-env CI=true node scripts/custom-config test --env=jsdom --findRelatedTests",
    "precommit": "lint-staged",
  },
   "lint-staged": {
    "**/src/**/*.js": [
      "prettier --write",
      "eslint --fix",
      "npm run test:staged",
      "git add"
    ]
  },
}
```

**Comment by kentcdodds** [comment]
That shouldn't be happening.

In your test do this:

```javascript
console.log(process.version)
console.log(Object.entries)
```

My guess is that your system is on a recent version of node, but somehow your tests are being run with an older version.

**Comment by nitish24p** [comment]
Did some digging.. Turns out husky was running the precommit script with some random old node version (6.9.4), not the same as my system, solved it my 
```bash
nvm alias default 8.12.0
```

**Comment by kentcdodds** [comment]
My guess is that you have an `.nvm` file in your project that's saying what version to run 😉

**Comment by nitish24p** [comment]
Naa, the library had some issues as enlisted here https://github.com/typicode/husky/issues/77
https://github.com/typicode/husky/issues/247
Anyway thanks :)
