### ISSUE TITLE
Unused variable in example code in docs

### ISSUE THREAD

**Issue by apaatsio** [kentcdodds/react-testing-library#115]
### Relevant code or config:

In the documentation at https://chrisnoring.gitbooks.io/react/content/testing/react-testing-library.html there is this example.

```js
it('load data', async() => {
    const {getByText, getByTestId, getByPlaceholderText, container} = render(<Select />);

    Simulate.click(getByText('Load'));
    await wait(() => getByTestId('data'))
    const data = getByTestId('data')
    const elem = getByTestId('item');
    expect(elem).toHaveTextContent('test');
  })
```

### Problem description:

The variable `data` is never used, so the line `const data = getByTestId('data')` is unnecessary since it doesn't have any effect on the outcome of the test.

### Suggested solution:

Remove the line `const data = getByTestId('data')`

**Comment by antoaravinth** [comment]
@apaatsio It would be great, if you can give us a PR. Will be happy to merge it.

**Comment by gnapse** [comment]
I'm confused. Isn't that code and the line to be removed in a documentation that's not part of this repo? Why would that be an issue to be raised in this repo then?

**Comment by antoaravinth** [comment]
@gnapse Yes you are right. I didn't notice the link properly. Closing the issue.

**Comment by apaatsio** [comment]
What is the correct repo for this issue?
