### ISSUE TITLE
engines config breaks deploys to Netlify

### ISSUE THREAD

**Issue by wKovacs64** [kentcdodds/react-testing-library#12]
* `react-testing-library` version: 1.4.0
* `node` version: 6.13.1
* `npm` (or `yarn`) version: yarn 0.18.1

Relevant code or config:

`react-testing-library` `package.json`:

```json
"engines": {
  "node": ">=8",
  "npm": ">=5"
},
```

What you did:

* deployed existing site to Netlify after adding `react-testing-library` to `devDependencies`

What happened: 

* Netlify deploy failed:
```
7:57:52 PM: error react-testing-library@1.4.0: The engine "node" is incompatible with this module. Expected version ">=8".
7:57:52 PM: error Found incompatible module
```

Problem description:

* `react-testing-library` uses a somewhat restrictive `engines` stanza in `package.json`

Suggested solution:

* relax the Node version requirement for `react-testing-library` to `4.5` (from [`kcd-scripts` babel config](https://github.com/kentcdodds/kcd-scripts/blob/7dd1f6a0364b9640d29d5984f3d5287b51b7430c/src/config/babelrc.js#L13)) or at least `6` ([active LTS](https://github.com/nodejs/Release/blob/master/README.md))?

**Comment by kentcdodds** [comment]
I'd be fine with 6. But why don't you upgrade to 8?

**Comment by wKovacs64** [comment]
In this particular case, I could, as Netlify provides a way to do that and I don't care about the Node version for my app. But I'd imagine scenarios exist where that's not possible, either due to lack of control of the runtime environment or app-specific target requirements or what-have-you. It seems like an odd and unexpected developer experience to require runtime environment changes to use such a small testing library when there's no underlying technical reason for it.

6 makes sense, I'll send a PR for it. Thanks!

**Comment by wKovacs64** [comment]
Oh. Just noticed this uses `Object.entries`. Thoughts?

**Comment by kentcdodds** [comment]
`kcd-scripts` shouldn't make any difference for whether you can use this library. This library doesn't depend on `kcd-scripts` (except as a dev dependency, which you shouldn't need to install). Now if you're _using_ `kcd-scripts` yourself, then yes, you'll have to use Node 8. That will never support less than Node 8.

**Comment by wKovacs64** [comment]
Yeah, I was mistakenly trying to run your `validate` script in `react-testing-library` on Node 6. Sorry for the confusion, lack of sleep and running on fumes today. 😄
