### ISSUE TITLE
Add JSDoc to typings for better DX in IDEs

### ISSUE THREAD

**Issue by MarkPollmann** [kentcdodds/react-testing-library#123]
### Describe the feature you'd like:
If I start typing library functions in VS Code all I see in the IntelliSense tooltip is the import statement: 

<img width="684" alt="sad-function" src="https://user-images.githubusercontent.com/5286559/41744883-d235ee4c-75ad-11e8-8957-4f55d06262dc.png">

As far as I know this could be easily fixed by adding JSDoc in the `typings/index.d.ts` file so the developer quickly sees a short overview of what this function does and which parameters are expected.

### Suggested implementation:

I can start annotating the exported functions 🙂

**Comment by kentcdodds** [comment]
Sounds good to me!

Though you should know that we no longer export `Simulate` :)

**Comment by MarkPollmann** [comment]
Oops, I confused myself reading the docs and watching your course on FEM in parallel 😅

**Comment by kentcdodds** [comment]
My bad 😅

**Comment by MarkPollmann** [comment]
If anyone with more experience in this wants to contribute, feel free to comment here. Else I'm going to take a stab at it on the weekend.
