### ISSUE TITLE
Add Kent's youtube video to README

### ISSUE THREAD

**Issue by farskid** [kentcdodds/react-testing-library#134]
**Thanks for creating this fantastic library!**

A question:

@kentcdodds just did a very good video on why you shouldn't be using shallow rendering. I found it very helpful in order to know the problems with shallow rendering. It also convinced my to user react-testing-library which before that, was not that clear for me.

Can we put that video on top part of the readme? I think it will help other people to have a overview of why this library helps them and what are the pitfalls of their current shallow rendering tests.

Video URL: https://www.youtube.com/watch?v=LHUdxkThTM0

Also a suggestion:

Can we also have this sentence in the repo description please? it makes it even more clear. at least for me it was helpful.
**This library is a replacement for enzyme!**

**Comment by antoaravinth** [comment]
@farskid : Good point. Can you raise a PR for the same? We would be happy to accept it. 👍

**Comment by gnapse** [comment]
I'd say is an **alternative** to enzyme, that also does not preclude using it alongside enzyme in the same project (though hopefully not both in the same tests at the same time!) Could seem crazy, but it's a valid path for those that want to migrate from enzyme to react-testing-library, and can only afford to do it gradually.

**Comment by antoaravinth** [comment]
@gnapse Well, I guess we no need to add any references to other libraries at all. We just say react-test-library allows you to write tests in better fashion in our docs and its user choice to pick it up or not.

**Comment by farskid** [comment]
@antoaravinth @gnapse Thanks for replying.
I'd send a quick PR to add the video link.
About the enzyme sentence, I picked it up from the readme! It's already there. so if you think it's not precisely true, I'd guess we should change it there too?

**Comment by kentcdodds** [comment]
It is true and we should call it out more. Perhaps it could be:

```md
> Note: react-testing-library is a complete replacement for enzyme (though you can use them in one codebase to migrate over time).
```

Something like that anyway...

**Comment by kentcdodds** [comment]
If we could make the YouTube link be one which has the devtips playlist that would be helpful: https://www.youtube.com/watch?v=LHUdxkThTM0&list=PLV5CVI1eNcJgCrPH_e6d57KRUTiDZgs0u
