### ISSUE TITLE
[4.1.3] Cannot find module 'jest-dom/extend-expect'

### ISSUE THREAD

**Issue by ryota-murakami** [kentcdodds/react-testing-library#138]
- `react-testing-library` version: 4.1.4
- `react` version: 16.4.1
- `node` version: 9.11.1
- `npm` (or `yarn`) version: yarn 1.3.2

### Relevant code or config:

```js
// occurring error this line
import 'jest-dom/extend-expect'
```
entire test code
https://github.com/ryota-murakami/redux-boilerplate-less-architecture/blob/master/src/pages/github/index.test.js

### What you did:
- [Depfu bot work](https://github.com/ryota-murakami/redux-boilerplate-less-architecture/pull/41/files)

### What happened:
Test Broke with `Cannot find module 'jest-dom/extend-expect'`

### Reproduction:
- In 4.1.3 case, the above Error occurred. https://circleci.com/gh/ryota-murakami/redux-boilerplate-less-architecture/569?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

- In 4.1.2 case, test is all green. (https://circleci.com/gh/ryota-murakami/redux-boilerplate-less-architecture/591?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

I don't know why is that happening because there is no `jest-dom` change [https://github.com/kentcdodds/react-testing-library/compare/v4.1.2...v4.1.3](between v4.1.2 
 v4.1.3).

something of dom-testing-liblary?
thanks😀

**Comment by kentcdodds** [comment]
You have to install jest-dom manually.
Good luck!

**Comment by ryota-murakami** [comment]
Thanks, it works😀

**Comment by jamie-kupka-acl** [comment]
I am having the same problem - what does "You have to install jest-dom manually." mean? Thanks.

**Comment by alexkrolick** [comment]
It's a separate package

```
npm install -D jest-dom
# or yarn
yarn add --dev jest-dom
```

**Comment by jamie-kupka-acl** [comment]
I've done that; its in my package.json (^3.1.3)

**Comment by nec286** [comment]
```
yarn add -D @testing-library/jest-dom
```

**Comment by s-Hale** [comment]
any update on this? There's still a lot of mixed info out there - jest-dom is now packaged in, toBeInTheDocument must come from jest-dom, jest-dom is deprecated, it's @testing-library/jest-dom now, you need to import it, you don't need to import it...   All the set-up guides are out of date.

If I ```import {toBeInTheDocument} from '@testing-library/jest-dom'``` then I'm told ```Cannot find module '@testing-library/jest-dom' ``` and if I don't then ```TypeError: expect(...).toBeInTheDocument is not a function```

**Comment by eps1lon** [comment]
@s-Hale Did you install `@testing-library/jest-dom`? Either via https://github.com/testing-library/jest-dom#installation or `yarn add -D @testing-library/jest-dom`

**Comment by nharrisanalyst** [comment]
I am still getting this error

I installed jest-dom manually (it should be mentioned in the docs that this package will not work without jest-dom)  beginners like me found this package first before jest-dom.

**Comment by nharrisanalyst** [comment]
I am still getting this error nothing is fixing it
OK I just got this error

jest-dom has moved to @testing-library/jest-dom. Please uninstall jest-dom and install @testing-library/jest-dom instead, or use an older version of jest-dom. Learn more about this change here: https://github.com/testing-library/dom-testing-library/issues/260 Thanks!

**Comment by stevenYouhana** [comment]
replace
import "jest-dom/jest-dom/extend-expect";
with
import "@testing-library/jest-dom/extend-expect";

**Comment by MadhavanPalani** [comment]
Step 1: Uninstall jest-dom(deprecated one)
npm uninstall jest-dom

Step 2:Install testing-library/jest-dom
npm i @testing-library/jest-dom

Step 3:Replace
import "jest-dom/jest-dom/extend-expect";
with
import "@testing-library/jest-dom/extend-expect";

Thanks @stevenYouhana

**Comment by proustibat** [comment]
If some of you still have the problem: I fixed it by using
```
import '@testing-library/jest-dom';
```
instead of `jest-dom/jest-dom/extend-expect`

This is the recommanded usage by the official [documentation](https://github.com/testing-library/jest-dom#usage)

**Comment by mdjahidhasan009** [comment]
> 

Thanks it works for me

**Comment by mdjahidhasan009** [comment]
> If some of you still have the problem: I fixed it by using
> 
> ```
> import '@testing-library/jest-dom';
> ```
> 
> instead of `jest-dom/jest-dom/extend-expect`
> 
> This is the recommanded usage by the official [documentation](https://github.com/testing-library/jest-dom#usage)

Thanks it works for me.

**Comment by tywallis** [comment]
I am still having this issue even after following all the instructions on this page.

I am trying to update my yarn dependency from jest-dom 5.17.0 to 6.1.4. I am already using `import "@testing-library/jest-dom";` in my setup.ts file. I don't specifically import `extends-expect` anywhere. When I run `yarn install`, it populates my node_modules with `import "@testing-library/jest-dom/extend-expect";` giving me the `Cannot find module '@testing-library/jest-dom/extend-expect' from 'node_modules/@fabric/core/lib/testing/setupTests.js'` error.
