### ISSUE TITLE
Update docs to remove toBeInTheDOM

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/react-testing-library#140]
Regarding the deprecation of `toBeInTheDOM` we should either find better assertions or use `toBeInTheDocument`: https://github.com/gnapse/jest-dom/pull/40

Anyone wanna try that?

**Comment by gnapse** [comment]
I'd like to.

BTW, it's not just the readme, there's a test using `toBeInTheDOM`. And this PR would also need to upgrade the jest-dom version (especially in the case where changing stuff involves needing to use `toBeInTheDocument`) right?

**Comment by kentcdodds** [comment]
Good point. Yes, we'll want to upgrade things 👍
