### ISSUE TITLE
Does it works with styled components?

### ISSUE THREAD

**Issue by albert-olive** [kentcdodds/react-testing-library#144]
Hi Kent,

I'm trying to use your fantastic library but I'm having an issue with the snapshots. I'm using styled components and now I don't see the styles in my snapshots. For example:

![image](https://user-images.githubusercontent.com/27954280/43073673-bb882a58-8e7a-11e8-9f07-fb20b54e69af.png)

I saw somewhere that you're using glamorous and you fixed that but, what about styled components?

Edit: I'm using [jest-styled-components](https://github.com/styled-components/jest-styled-components).

Thanks

**Comment by kentcdodds** [comment]
I would report this issue on jest-styled-components. I'm guessing their snapshot serializer doesn't work for DOM elements like glamorous and emotion do.

You could point them to these functions which make them support HTML strings as well as DOM nodes: https://github.com/kentcdodds/jest-glamor-react/blob/61cb3d0d7acef4f34128a7d3a75f60ebc97730e2/src/serializer.js#L75-L101

Good luck!

**Comment by Vandell63** [comment]
Hey, @albert-olive i faced the same issue using Material React ui with jss... but in this case all jss generate a specifique generated classname. The way i did :
- Only specify static css on jss style
- Dynamic Css for React inline style from props or state

@kentcdodds a question about this : what's the better way to handle dynamic style in your library if props change ? :
```
expect(Component.style._values["background-color"]).toBe("rgb(244,244,244)")

// or ( for me the wrong way cause of changing style order may break this test right ? )
expect(Component.style[0])toBe("rgb(244,244,244)")
```
