### ISSUE TITLE
Do you think to make a website for documentation?

### ISSUE THREAD

**Issue by glauberfc** [kentcdodds/react-testing-library#155]

**Comment by glauberfc** [comment]
Yes, I like. Could we use Gatsby for this task?
Is the content the same those on Github?

**Comment by glauberfc** [comment]
I liked this idea, but I didn't understand well what is "defendants tab".
Could you organize the content of site on a repository?
Do the project has an official logo?

**Comment by kentcdodds** [comment]
Sorry, I meant "dependants tab"

<img width="1200" alt="screen shot 2018-08-10 at 10 00 27 am" src="https://user-images.githubusercontent.com/1500684/43968405-3bccc04a-9c84-11e8-8e6d-da11b59a72fc.png">

Not all of those need to be documented with dom-testing-library, but these definitely could:

- cypress-testing-library
- react-testing-library

And we could invite the authors of these libraries to contribute docs for their libraries to the site as well:

- pptr-testing-library
- bs-dom-testing-library
- vue-testing-library
- preact-testing-libraryng-testing-library
- ngx-testing-library

I _think_ that I'd really like the docs written in mdx with https://github.com/ChristopherBiscardi/gatsby-plugin-mdx

There's no official logo. If you could get things started with the site, then I can start contributing content for the docs :) Let's go ahead and start with having the site be part of this repo. You can put it in a `website` directory with its own `package.json`. We can move it to its own repo later :)

Thanks!

**Comment by glauberfc** [comment]
Ok, Kent.  I will try to begin the project as soon as possible.

**Comment by antsmartian** [comment]
@kentcdodds That sounds a great idea. I have authored `preact-testing-library` (you knew it ;)) and I can work on the documentation part for the same!

**Comment by glauberfc** [comment]
What do you think guys? Sincerity, please!

![home](https://user-images.githubusercontent.com/15311858/44117624-3841fddc-9fea-11e8-9309-4de298861a7c.png)

**Comment by kentcdodds** [comment]
This is such a fantastic start! Keep going and posting screenshots/demos. I'll give more feedback when I can.

**Comment by glauberfc** [comment]
I need ideas for other sections

**Comment by alexkrolick** [comment]
Well, the most important part is the docs page... So maybe get started on the API reference?

**Comment by ematipico** [comment]
Nice job!

**Comment by glauberfc** [comment]
@kentcdodds What you think about add more three sections after "Some advantages" section:  1. Video overview, 2. Contributors or Sponsors, and 3.Who's using the library?

**Comment by kentcdodds** [comment]
Yes, all three of those would be cool :+1:

**Comment by bsotodo** [comment]
looking great!

**Comment by Lukeghenco** [comment]
@glauberfc any progress on this or ways I can get involved with documentation site. Big supporter of these projects and want to help out if I can.

**Comment by glauberfc** [comment]
I'm sorry guys. I needed to travel and ended up don't finishing the layout. I will finish asap, so we can discuss how we can implement and grow it. Thanks for help @Lukeghenco

**Comment by glauberfc** [comment]
What you think guys? Sorry by the typos

![home](https://user-images.githubusercontent.com/15311858/45721332-0e00b180-bb7e-11e8-822e-c380defa2eb2.jpg)

**Comment by kentcdodds** [comment]
I think it's a great start! We can start here and iterate from there :)

**Comment by hloughrey** [comment]
Would love to get involved - think this is a great library and would like to help promote it!

**Comment by glauberfc** [comment]
May I init the project with Gatsby?

**Comment by kentcdodds** [comment]
I've been thinking about how I want to do this... This site will be used to document all of the *-testing-library projects that want to take part. So I think it would be best to be in its own repo. Perhaps eventually I'll make a GitHub org for repos such as this, but I don't want to do that at the moment. For now, why don't you just create the repo under your own user @glauberfc? Then we can move it later if we decide to.

**Comment by glauberfc** [comment]
Ok, @kentcdodds, I'll do. When you make the repo I going to move the files to it.

**Comment by kentcdodds** [comment]
> When you make the repo I going to move the files to it.

Sorry, to be clear I was saying that _you_ can make the repo :) Just link to it here and I'll start following progress there :)

**Comment by glauberfc** [comment]
Sorry! I meaning that if some day you make a Github org repo I going to transfer the files to it.

**Comment by glauberfc** [comment]
@kentcdodds do you have some tip or article link about how use Styled Components in an organized way or showing "the right way" of use it?

**Comment by tzehe** [comment]
Hey! Thank you for this awesome library. If you need a helping hand than I would like to support you.
Keep up the good work!

**Comment by kentcdodds** [comment]
Sweet, here's the repo: https://github.com/glauberfc/dom-testing-library-website

I'm watching that repo. I'm going to go ahead and close this issue and we can continue discussion over there. Thanks!
