### ISSUE TITLE
Entire error output to console during a .toThrow() assertion

### ISSUE THREAD

**Issue by good-idea** [kentcdodds/react-testing-library#157]
- `react-testing-library` version: 5.0.0
- `react` version: 16.4.2
- `node` version: 8.11.3
- `npm` (or `yarn`) version: yarn 1.9.4

### Relevant code or config:

```js
const Component = props => {
	if (props.throw) throw new Error('!!')
	return <div>😀</div>
}
```

```js
it('Throws an error when `props.throw === true`', () => {
	const renderComponent = () => render(<Component throw />)
	expect(renderComponent).toThrow('!!')
})
```
### What you did:

I'm making a jest assertion that a component will throw an error under certain circumstances.

### What happened:

While the test itself passes, the entire error shows up in the Jest output. Under other circumstances, jest suppresses errors that are thrown within a `.toThrow()` assertion. (there's a test in the repo that shows this)

### Reproduction:

https://github.com/good-idea/rtl-throws-error

### Problem description:

Lots of unnecessary console output!

### Suggested solution:

I haven't looked into how jest / RTL handles all of this and how it might be happening, but I'm happy to put together a PR. Just point me in the right direction!

**Comment by kentcdodds** [comment]
This actually is not something that has anything to do with react-testing-library. It's how react and jsdom work. You can silence these logs using mock functions. That's what I do.

**Comment by good-idea** [comment]
Oh, got it ~ I hadn't come across this until I started using react-testing-library so I thought it was a problem on that side.

Thanks for the quick response!

**Comment by good-idea** [comment]
For anyone else coming here with the same problem, putting this in my setup file has it work exactly as I'd expect:

```js
console.error = err => { throw new Error(err); };
console.warn = warning => { throw new Error(warning); };
```

**Comment by wheelmaker24** [comment]
> This actually is not something that has anything to do with react-testing-library. It's how react and jsdom work. You can silence these logs using mock functions. That's what I do.

For everyone wondering: This is an easy way to do it: https://til.hashrocket.com/posts/hrhejhqg2n-turn-off-console-error-messages-in-a-test
