### ISSUE TITLE
Encourage using aria selectors

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/react-testing-library#16]
I've been in a discussion @neoziro on my blog where [he suggests](https://medium.com/@gregberge/yes-i-think-adding-a-aria-instead-of-a-data-test-is-much-more-valuable-for-the-user-c6e021b0be21) using `aria-` attributes and text content instead of `data-testid`. He makes great points and I think that it would be great if this library could provide selectors to encourage this behavior. I'm thinking that aria attributes wont always make sense for every test, in which case we could fallback to `data-testid`, and for [localization reasons](https://medium.com/@kentcdodds/im-glad-it-s-working-for-you-89210d06c438) text content may not make the most sense either, but making it easier to select based on text content could still make sense for some use cases and we could explain what those are.

So, out of this issue, I'd like to see some examples of what it would take to make utilities for selecting based on aria attributes as well as text content. If it works out, then we could recommend the following order of preference for selecting:

1. Text Content (99% of your users will be using your app by looking at the text content, so if you don't have issues with localization then this should be the best)
2. `aria-` attributes (your app should be accessible anyway, and this would encourage that as well).
3. `data-testid`s because they're way better than using class names, dom structure, or querying by React component classes.

Anyone want to try doing this?

**Comment by theKashey** [comment]
It always was a little problem - what to check and how to select.
 - `data-testid` is great, as long you could remove them in production.
 - `aria-` attributes is even better, as long they are _describing_ an element
 - text matches? - awesome, cos check that user will see something expected - is the only thing you have to test.

Meanwhile
 - `data-testid` does not reflect that the customer will see. They are _dead_ selectors.
 - `aria-` stuff __shall not__ be used for testing purposes. Aria stuff should be used only to help browser understand or override the default behaviour.
> If you need a button - use <button/> not `role`. Aria-disabled? Just disabled. In real it is a quite rare condition when you __have__ to use _aria_, better use correct and semantic markup.
 - `text content` matches are not very _specific_, sometimes very flexible, sometimes you need that flexibility.

So - I could 90% agree with you. Text Content to test content, data-testid to test DOM structure, if you need to test it.
Just be a bit more careful with aria stuff. Do not prevent browser to infer _the right_ behaviour by its own.

**Comment by kentcdodds** [comment]
You bring up good points @theKashey. I worry that if we start encouraging using `aria-` attributes, people will start slapping them on where they don't belong. If we do text matches, then I'd want our abstraction to be pretty loose (maybe allow for a regex search?).

**Comment by kentcdodds** [comment]
Alrighty, so I've written out a few utilities that have proven to be pretty useful and sensible. I think I want to put them in the library. I'm sure there are more (especially for more `aria-` attribute associations like the `aria-labelledby` one here). Feedback welcome:

```javascript
function queryByLabelText(container, text, {selector = '*'} = {}) {
  const label = Array.from(container.querySelectorAll('label')).find(l =>
    matches(l.textContent, text),
  )
  if (!label) {
    return null
  }
  if (label.getAttribute('for')) {
    // <label for="someId">text</label><input id="someId" />
    return container.querySelector(`#${label.getAttribute('for')}`)
  } else if (label.getAttribute('id')) {
    // <label id="someId">text</label><input aria-labelledby="someId" />
    return container.querySelector(
      `[aria-labelledby="${label.getAttribute('id')}"]`,
    )
  } else if (label.children.length) {
    // <label>text: <input /></label>
    return label.querySelector(selector)
  }
  throw new Error(`cannot find associated element for label with text ${text}`)
}

function queryByText(container, text, {selector = '*'} = {}) {
  return Array.from(container.querySelectorAll(selector)).find(
    node => !node.children.length && matches(node.textContent, text),
  )
}

function queryByPlaceholder(container, text) {
  return Array.from(container.querySelectorAll('[placeholder]')).find(
    node =>
      node.getAttribute('placeholder') &&
      matches(node.getAttribute('placeholder'), text),
  )
}

function matches(textToMatch, matcher) {
  if (typeof matcher === 'string') {
    return textToMatch.toLowerCase().includes(matcher.toLowerCase())
  } else if (typeof matcher === 'function') {
    return matcher(textToMatch)
  } else {
    return matcher.test(textToMatch)
  }
}
```

**Comment by kentcdodds** [comment]
I'm working on this right now, just FYI. We'll have several handy utilities for this stuff when I'm finished :)

**Comment by theKashey** [comment]
I’ll prefer to write the usage of a new stuff first. 
Create some cases, and try to solve them with a better API and thus find that better API and the better practices.

**Comment by kentcdodds** [comment]
That's where these utilities came from. I'm applying them to tests in another project. It's cleaning things up nicely 👌

**Comment by aciccarello** [comment]
I don't have much experience testing React but @jgwhite [gave a talk recently](https://youtu.be/qfnkDyHVJzs?t=5h39m19s) at EmberConf that is related. I wonder if there is a good generalized aria-aware query library that could be used in tests across frameworks.

![ember conf talk slide showing a "find control for label" test helper function](https://user-images.githubusercontent.com/11273838/37813723-0323b5ee-2e2c-11e8-9488-18a0639b5670.png)

**Comment by kentcdodds** [comment]
Thanks for that link @aciccarello! @jgwhite that was a great talk! That's exactly what I'm trying to accomplish in this issue and your talk was very validating. Thank you!

**Comment by jgwhite** [comment]
@kentcdodds it is really really exciting (and also validating) to see you working on the same ideas. I’m starting work on a formal RFC for Ember’s testing toolkit next week and I’ll be sure to reference this as prior art! 

Thanks to @aciccarello for making the connection 🙌

**Comment by aciccarello** [comment]
I'm glad to see connections made. I'd like to see this pattern brought into test Angular applications as well. :+1: to everyone who has been working on this.

**Comment by Pau1fitz** [comment]
Am I missing something stupid here?

Code snippet below, and a screenshot of the error.

```
<form onSubmit={login}>
   <label htmlFor='username'>Username</label>
   <input 
        type='text'
        name='username' 
        value={form.username}
        onChange={updateField}
    />
    <input type="submit" />
</form>
```


<img width="787" alt="screenshot 2018-12-07 at 13 01 33" src="https://user-images.githubusercontent.com/6873736/49649169-41860600-fa20-11e8-8a4e-9fcbf011c92a.png">
