### ISSUE TITLE
React Testing Library Course Examples

### ISSUE THREAD

**Issue by vctormb** [kentcdodds/react-testing-library#188]
### Describe the feature you'd like:
Is it possible to put all the examples from [react testing library course](https://github.com/kentcdodds/react-testing-library-course) here in the examples folder? 
It is helping me a lot and I think that it will help everybody too!

Thanks!

**Comment by kentcdodds** [comment]
Sorry, no, but you can feel free to make a PR to add a link to them in the README.

I'm glad it's helping you!

**Comment by vctormb** [comment]
I'll do it! Thanks!
