### ISSUE TITLE
External resource loading and side effects

### ISSUE THREAD

**Issue by PWesterdale** [kentcdodds/react-testing-library#195]
- `react-testing-library` version: 4.1.2
- `react` version: 16.2
- `node` version: 9.11
- `yarn` version: 1.60

### Relevant code or config:

```js
class PlaceheldImage extends React.Component<IPlaceheldImageProps, IPlaceheldImageState> {
    state = {
        loaded: false,
        error: false
    };
    componentDidMount()
    {
        const loadImage : HTMLImageElement = new Image();
        const callback : EventListener = (evt : Event) => {
            this.setState({ loaded : true, error : (evt.type === 'error') });
        }
        loadImage.onload = callback;
        loadImage.onerror = callback;
        loadImage.src = this.props.imgSrc;
    }
    renderComplete() {
        return this.state.error ? <div /> : <img data-testid="loaded-image" src={this.props.imgSrc} alt={this.props.imgAlt} />;
    }
    render() {
        return (
            <div>
                {this.state.loaded ? this.renderComplete() : <Spinner />}
            </div>
        )
    };
};
```

### What you did:
Pre-loading an external image in code before adding the image node to the dom.

### What happened:
image.onload does not get called and therefore does not complete

### Problem description:
I would expect react-testing-library to have a flag or something that will enable external fetching of assets for rendered components.

**Comment by Gpx** [comment]
Hi, I had the same problem a few weeks ago. In the end, I just changed the component so that if `process.env.NODE_ENV === 'testing'` it fakes the load of the image. Probably not the solution you were looking for, but it unblocked me.

**Comment by kentcdodds** [comment]
Hi,

I think this is outside of the scope of react-testing-library and this issue should probably be filed on JSDOM. I'm guessing that's where the problem lies. Good luck!
