### ISSUE TITLE
Can test React component using less module style ?

### ISSUE THREAD

**Issue by congdcit** [kentcdodds/react-testing-library#202]
I'm using less module in React Component.
But I don't know how to config to run it.
Please guide me!

**Comment by kentcdodds** [comment]
I'm not 100% certain I understand what you mean by "less module style." If you're saying that you're using CSS modules with Less though... Well, that's kind of a big subject. I'm actually releasing a testing course soon that might be helpful: [testingjavascript.com](https://testingjavascript.com). I don't talk about less specifically, but it does have content about css modules. You may find something useful in the material: https://github.com/kentcdodds/jest-cypress-react-babel-webpack

I hope that helps... Good luck!
