### ISSUE TITLE
onChange not being called on controlled input when using fireEvent.change()

### ISSUE THREAD

**Issue by dadamssg** [kentcdodds/react-testing-library#203]
- `react-testing-library` version: 5.2.0
- `react` version: 16.4.2
- `node` version: 8.11.1
- `npm` (or `yarn`) version: 1.6.0

### Relevant code or config:

```js
test('Filters list', () => {
  const {getByTestId, getByPlaceholderText, queryByTestId} = render(<Example />)
  // foo item should exist initially
  getByTestId('foo')
  const input = getByPlaceholderText('Filter')
  // add filter text
  fireEvent.change(input, {target: {value: 'ba'}})
  // ensure the input has the filter value typed
  expect(input.value).toBe('ba')
  // expect that foo should not be in the list now
  expect(queryByTestId('foo')).toBeNull()
  // ^ fails because input onChange handler was not called and setState never occurred
})

```

### What you did:

Attempt to use `fireEvent.change()` to trigger a change handler

### What happened:

![image](https://user-images.githubusercontent.com/881986/47177325-bfaa1400-d2dd-11e8-97dd-75ef63489d6a.png)

### Reproduction:

https://codesandbox.io/s/nnw46j1j3l

### Problem description:

The change handler on a controlled input is not being called.

**Comment by gnapse** [comment]
In the code snippet you are posting above, `const onChange` is declared, but never used.

**Comment by dadamssg** [comment]
@gnapse you're right about the `onChange` not being used. That was left over code. I've updated the sandbox.

The code sandbox shows that the input should filter the list. That is happening during manual testing as you can see. However, the test that does that same thing is failing because the `onSearch` is not being called which is responsible for updating the component state.

**Comment by gnapse** [comment]
Again, I think there's a smell around you having the `ReactDOM.render` line inside the same file you're importing in your test. You should not do this. You should have that in a separate file that is not loaded in tests.

The reason react-testing-library is still finding the item, is because you're rendering an extra version of your Example component, in addition to the one that you are trying to test.

Comment out the `ReactDOM.render` line and your tests will pass.

**Comment by dadamssg** [comment]
well shoot. you're right. i have no idea why this is happening for me locally then. dangit
