### ISSUE TITLE
Can you rename `data-testid` to `data-test-id` because I am OCD?

### ISSUE THREAD

**Issue by bpkennedy** [kentcdodds/react-testing-library#204]
Not sure why we can't hyphenate the whole thing is all.  😄

**Comment by gnapse** [comment]
Please see kentcdodds/dom-testing-library#76

**Comment by 6ewis** [comment]
How about we allow for both `data-testid` (and eventually deprecate it) and 'data-test-id`(which is more intuitive)

**Comment by kentcdodds** [comment]
Sorry, no. We're going to stick with what we have. You can create a custom query and pass it as an argument to dom-testing-library and use that one instead if you want. Thanks anyway!

**Comment by Gpx** [comment]
> You can create a custom query and pass it as an argument to dom-testing-library and use that one instead if you want.

Would it be OK if I add a section in the README explaining how to make such a query?

**Comment by kentcdodds** [comment]
Yes, please do @Gpx!

**Comment by ankitsinghaniyaz** [comment]
The example on the readme doesn't seem to work.

```javascript
// test-utils.js
import {render, queryHelpers} from 'react-testing-library'

export const queryByTestId = queryHelpers.queryByAttribute.bind(
  null,
  'data-test-id',
)
export const queryAllByTestId = queryHelpers.queryAllByAttribute.bind(
  null,
  'data-test-id',
)

export function getAllByTestId(container, id, ...rest) {
  const els = queryAllByTestId(container, id, ...rest)
  if (!els.length) {
    throw getElementError(
      `Unable to find an element by: [data-test-id="${id}"]`,
      container,
    )
  }
  return els
}

export function getByTestId(...args) {
  return queryHelpers.firstResultOrNull(getAllByTestId, ...args)
}

const customRender = (node, ...options) => {
  const utils = render(node, ...options)

  return {
    ...utils,
    getByTestId: getByTestId.bind(container),
    getAllByTestId: getAllByTestId.bind(container),
    queryByTestId: queryByTestId.bind(container),
    queryAllByTestId: queryAllByTestId.bind(container),
  }
}

// re-export everything
export * from 'react-testing-library'

// override render method
export {customRender as render}
```

Here are the two issues that I see:

1. `container` is not defined int he `customRender` method
2. At runtime I get an error saying `TypeError: container.querySelectorAll is not a function` for line 17
`const els = queryAllByTestId(container, id, ...rest)`

**Comment by alexkrolick** [comment]
Woops

- change `node` to `container`
- should be queryHelpers.getElementError

PR appreciated

**Comment by ankitsinghaniyaz** [comment]
Cool, I'll create a PR for this.

**Comment by psyshush** [comment]
the ability has been added to the library, see [here](https://testing-library.com/docs/dom-testing-library/api-configuration)
