### ISSUE TITLE
Drop dependency on React's Simulate module

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/react-testing-library#206]
This code has got to go:

https://github.com/kentcdodds/react-testing-library/blob/fe3b65ca158f0ac088b67b195b678a9428a7a2b5/src/index.js#L62-L68

I'm not sure what is needed, but I suggest that we methodically remove one element from that array, see what breaks, then add some code until it starts working.

It may mean that we continue to monkey-patch `fireEvent` to support React events properly (because React is a little special). All I really care about is getting rid of the Simulate module. The biggest reason is #129, but also Dan told me we shouldn't use it and it's hacky and I want to get rid of it :)

**Comment by weyert** [comment]
When you say doesn't work in the DOM you are referring to `jsdom` correct? As far as I know the mouse enter and mouse leave events exists as they are mentioned on MDN. The JSDOM does define the `MouseEvent` at: https://github.com/jsdom/jsdom/blob/13b2326b57ec621c4b75a64966ea23d89d8fce99/lib/jsdom/living/events/MouseEvent-impl.js

**Comment by kentcdodds** [comment]
I think that comment is referring to the fact that they don't work in the same way the DOM works.

If you remove them from the array, you'll notice that tests start to break. Try to fix the tests without changing the tests. That's the task at hand :)

**Comment by weyert** [comment]
I have been looking into this for a bit I find potentially relevant or interesting unit tests in the React repository: 

https://github.com/facebook/react/blob/b87aabdfe1b7461e7331abb3601d9e6bb27544bc/packages/react-dom/src/events/__tests__/EnterLeaveEventPlugin-test.js
and 
https://github.com/facebook/react/blob/b87aabdfe1b7461e7331abb3601d9e6bb27544bc/packages/react-dom/src/events/__tests__/SelectEventPlugin-test.js

**Comment by kentcdodds** [comment]
@sivkoff fixed this! Thank you Vitaly!

**Comment by sivkoff** [comment]
@kentcdodds you're always welcome!
