### ISSUE TITLE
`.bind` calls in custom renderer docs pass container as 'this' value, not first param

### ISSUE THREAD

**Issue by RoystonS** [kentcdodds/react-testing-library#225]
The library README includes the following bit of sample code when suggesting how to write a custom renderer in order to change the 'testid' attribute:

```javascript
const customRender = (container, options) => {
  const utils = render(container, options)

  return {
    ...utils,
    getByTestId: getByTestId.bind(container),
    getAllByTestId: getAllByTestId.bind(container),
    queryByTestId: queryByTestId.bind(container),
    queryAllByTestId: queryAllByTestId.bind(container),
  }
}
```

I might have got completely the wrong end of the stick, but should those `.bind()` calls not have en extra first `null` parameter?  Otherwise they're passing `container` in as the `this` value to those functions rather than as the first parameter, as I think is intended?

### Suggested solution:

Change them all to `.bind(null, container)`

Happy to submit a PR...

**Comment by alexkrolick** [comment]
Right... Let's just change to arrow functions instead of bind.

**Comment by RoystonS** [comment]
i.e.

```javascript
getByTestId: (...rest) => getByTestId(container, ...rest),
```
and so on...?

I'll get a custom renderer together (as we have used `data-uia` for our test ids for years), check it works, and submit a PR...

**Comment by RoystonS** [comment]
... and in fact I think it also needs to be:

```javascript
getByTestId: (...rest) => getByTestId(utils.container, ...rest),
```
because we need to work with the actual container that was used, not just the incoming value (which might not be defined).  (This just bit me in the real renderer I'm writing.)

I'll keep going until I have a custom renderer that _works_ and then feed back.
