### ISSUE TITLE
Uncontrolled input value mutation

### ISSUE THREAD

**Issue by nadavkaner** [kentcdodds/react-testing-library#227]
Hi everyone, 

How i can test uncontrolled input component? 
I need to change the text of the input, and I tried to set directly the value of the dom node but the value is not changing and also to fire change event.
it looks like react does not know about the change of the input dom value.

Thanks.

**Comment by kentcdodds** [comment]
Hi 👋

This is documented here: https://github.com/kentcdodds/react-testing-library/blob/master/README.md#fireeventnode-htmlelement-event-event

Good luck!

**Comment by nadavkaner** [comment]
Hi Kent,

This document talk about controlled components and not uncontrolled input component.
when i trigger onChange event the value of the input is not changing, and also when i set the value property on the input dom node.

Thanks for the answer.

**Comment by kentcdodds** [comment]
Hmmmmm... Could you reproduce the issue in this codesandbox? https://kcd.im/rcs

**Comment by nadavkaner** [comment]
I did it, you can see it here: https://codesandbox.io/s/pkzp6xo87x

**Comment by FredyC** [comment]
I am going to hijack this issue because I am trying to solve exactly the same thing.

Here is a simplified reproduction: https://codesandbox.io/s/3858vjrjpp

The `onChange` is never triggered by tests for some reason.

**Comment by nadavkaner** [comment]
Just change the way you fire the event to this:
`fireEvent.change(input, {
    target: { value: "CHANGED VALUE" }
  });`

**Comment by FredyC** [comment]
@nadavkaner If you look closely, I am not using regular `ev.target.value` :) It's ref based approach mostly because of the TypeScript reasons.

**Comment by nadavkaner** [comment]
The trigger event also change the value of the input, so this is also work.. 
This resemble the way your user will interact with this component in the real world

**Comment by FredyC** [comment]
Wow, did not see that coming. You are completely right, it works. Thanks!

It could be probably mentioned in the docs that it will also modify the actual value of the input.
