### ISSUE TITLE
Wrong typings for queries by attribute

### ISSUE THREAD

**Issue by FredyC** [kentcdodds/react-testing-library#239]
- `react-testing-library` version: 5.3.1
- `react` version: 16.7.0-alpha.2
- `typescript` version: 3.2.1
- `node` version: 10.12.0
- `yarn` version: 1.10.1

### Relevant code or config:

```js
const { queryByRole } = render(<Something />)
expect(queryByRole('alertdialog')).toBeFalsy()
```

### What you did:

As you can see there is argument called `text`, but it's of `HTMLElement` type.

![image](https://user-images.githubusercontent.com/1096340/49699470-0a575680-fbd2-11e8-8b04-6948cac75646.png)

Tried the following to satisfy typings, but then it fails in runtime with error `TypeError: matcher.test is not a function` apparently because the `container` is nor string or a function, so it expects the RegExp.

![image](https://user-images.githubusercontent.com/1096340/49699553-d6c8fc00-fbd2-11e8-9918-0a0c912d98f8.png)

### Reproduction:

I would create one, but CodeSandbox for TypeScript is rather wonky and doesn't work correctly every time. I think that images above are a clear reproduction :) Whole repo is probably overkill

### Problem description:

It's rather curious that `getByRole` has no such issue.

![image](https://user-images.githubusercontent.com/1096340/49699645-eeed4b00-fbd3-11e8-8bfd-f42734c79d23.png)

### Suggested solution:

I tried to look into it, but my current mental capacity cannot cover this. For once I don't get how `getByRole` is typed correctly without any modification on `react-testing-library` side, but queries are wrong. This is some advanced TypeScript technique I am failing to comprehend.

@jpavon @pbomb Looks like you touched that part before. Do you have some insight perhaps?

**Comment by jpavon** [comment]
@FredyC I just tried a clean install and works for me: 

react-testing-library  5.3.1
react 16.6.3
typescript 3.2.2

<img width="650" alt="screen shot 2018-12-09 at 21 15 05" src="https://user-images.githubusercontent.com/1493505/49702350-86b06080-fbf7-11e8-8ba0-9c1247374820.png">

**Comment by pbomb** [comment]
Thanks @jpavon. Does this mean that we should close this issue? Or is there still a problem?

**Comment by FredyC** [comment]
@jpavon Thanks for looking into it. I don't get it. I just tried the separate project, all the same versions and it indeed works. Only my actual project it doesn't. And it's not like VSCode would go wonky. Even when I try running TSC, I get the same...

```
TS2345: Argument of type '"alertdialog"' is not assignable to parameter of type 'HTMLElement'
```

I've even used exactly same tsconfig.json just to be sure and still it works in that simple project.

I guess I will keep digging to be able reproduce this.

**Comment by kentcdodds** [comment]
Ah, looks like this is a yarn limitation. There's a workaround here: https://github.com/yarnpkg/yarn/issues/4986#issuecomment-395036563

**Comment by FredyC** [comment]
Yea sure, I can update lockfile manually, but is it really the best way? I mean it won't hurt anyone to set this hard dependency here and possible help some people that might encounter same issue in the future.

**Comment by noinkling** [comment]
@FredyC For posterity, doing a simple `yarn upgrade react-testing-library` (even if there isn't a new version) should update its dependencies. In this case that would just be `dom-testing-library` since it's the only dependency. For NPM I believe you would have to do something like `npm update react-testing-library --depth=1`.

If this package had more dependencies it would also try and update those, so it's less specific than the above workaround where you remove a piece of your lockfile, but also less hacky. And it's still more specific than deleting the whole lockfile.

**Comment by FredyC** [comment]
@noinkling Well, hard to test that now since the latest version has a correct dependency now. Are you sure about it? The issue linked by Kent above is exactly about that. Running `upgrade` won't modify indirect dependencies ... https://github.com/yarnpkg/yarn/issues/4986

Personally, I haven't been using a command line for this, I usually just change numbers in package.json simply because it's more apparent what has been updated and to what version when I look in git history. It's definitely not that apparent from lock file. Also, it's super easy with [VSCode Version Lens](https://marketplace.visualstudio.com/items?itemName=pflannery.vscode-versionlens).

Either way, the point here still remains that if a dependent library introduces breaking changes (although rather subtle in this case) it should always be updated in parent packages and not to rely on version ranges only.
