### ISSUE TITLE
afterEach cleanup not clearing the DOM

### ISSUE THREAD

**Issue by microcipcip** [kentcdodds/react-testing-library#241]
- `OS`: Win10
- `Command line env`: WSL (Windows subsystem for Linux)
- `react-testing-library` version: ^5.3.2
- `react` version: ^16.6.3
- `node` version: v11.2.0
- `npm` version: 6.4.1

### Relevant code or config:

This is my utils file
```js
import React from 'react'
import { render } from 'react-testing-library'
import 'jest-styled-components'
import 'jest-dom/extend-expect'
import MyContext, { MyContextState } from 'components/MyContext'

const customRender = (node, data = {}) => {
  return render(
    <MyContext.Provider value={Object.assign(MyContextState, data)}>
      {node}
    </MyContext.Provider>
  )
}

export * from 'react-testing-library'
export { customRender }
```

This is a simple test that fails.
```js
import { customRender, cleanup } from 'utils/testUtils'
import { myDataSample } from 'utils/myDataSample'
import MyComponent from '../MyComponent'

afterEach(cleanup)

it('Should create snapshot', async () => {
  const { container } = customRender(<MyComponent />, { myDataSample })
  expect(container).toMatchSnapshot()
})

it('Should not find element when myDataSample is not provided', async () => {
  const { getByText } = customRender(<MyComponent />) // Note: data not provided
  getByText('Some Text') // FOUND!
})

```

### What you did:

I tried to get a text that should not be there, but it is found although the `afterEach(cleanup)`. I tried everything to remove the DOM but I am unable to do so.

**Comment by kentcdodds** [comment]
What does `<MyComponent />` do?

**Comment by microcipcip** [comment]
@kentcdodds I am going to create a test repo.

**Comment by microcipcip** [comment]
I've tried anything to reproduce it but I am unable, on a vanilla CRA it works all right, I'll let you know if I manage to find how I got the conflict.
