### ISSUE TITLE
Ant design menu doesn't get rendered correctly into the DOM 

### ISSUE THREAD

**Issue by IsaaX** [kentcdodds/react-testing-library#243]
- `react-testing-library` version: 5.3.1 (or 5.3.2)
- `react` version: 16.5
- `node` version: 10.10
- `npm` (or `yarn`) version: 1.12.3

### Relevant code or config:

https://codesandbox.io/s/88ppllz180
```javascript
import React from "react";

import {
  render,
  cleanup,
  fireEvent,
  waitForElement
} from "react-testing-library";
import { Menu, Icon } from "antd";

const SubMenu = Menu.SubMenu;
const MenuItemGroup = Menu.ItemGroup;

afterEach(cleanup);

test("calls with user email and password", async () => {
  const app = render(
    <Menu
      onClick={() => {}}
      style={{ width: 256 }}
      mode="vertical"
      forceSubMenuRender={false}
    >
      <SubMenu
        key="sub4"
        title={
          <span>
            <Icon type="setting" />
            <span>Navigation Three</span>
          </span>
        }
      >
        <Menu.Item key="9">Option 9</Menu.Item>
        <Menu.Item key="10">Option 10</Menu.Item>
        <Menu.Item key="11">Option 11</Menu.Item>
        <Menu.Item key="12">Option 12</Menu.Item>
      </SubMenu>
    </Menu>
  );

  const { container, getByTestId, getByText, debug, rerender } = app;

  const nav = await waitForElement(() => getByText("Navigation Three"));
  fireEvent.mouseEnter(nav);
  debug();
});

```

### What you did:

Well after stumbling on your library, it seems like a great solution! One issue that I encountered was testing with the use ant-design. Specifically, I'm trying to create a `Menu` that contains a `SubMenu` component, and do a `fireEvent.mouseOver` to invoke the submenu to be displayed just how a user would use the component. The submenu that I'm using will be used around a HOC so wanted to test the data inside of it as well as ensure that the proper classes were on the correctly elements. 

### What happened:

When using the `debug` function provided by this module, I was looking at the DOM to see the changes update correctly but that doesn't seem to be the case. It'll partially update meaning when I dispatch the `fireEvent.mouseOver`, the element that I hover over receives the `.ant-menu-submenu-active` class name correctly but the `aria-expaned="false"` doesn't get updated correctly nor does the submenu get rendered into the DOM. Under the `Menu` component there is a prop named `forceSubMenuRender={false}` and when it's changed to true, it'll render the submenu correctly but once more, it doesn't remove the proper css classes needed in order to display the submenu. It's probably due to the lack of understanding how all of this works in conjunction so was wondering if you can help point me in the right direction. I really like the concept behind this library and want to commit to using this. 

I know that the `fireEvent.mouseOver` is working correctly because when I comment it in/out the `.ant-menu-submenu-active` class does get inserted/removed correctly. 

### Reproduction:

https://codesandbox.io/s/88ppllz180

### Problem description:

It doesn't allow me to unit tests certain parts of my frontend meaning lower confidence in my test suite.  Figured this might be a common theme 

### Suggested solution:

I wish I could make a recommendation but this is out of the scope of my knowledge.

**Comment by jakobsandberg** [comment]
Hi @IsaaX, thank you for providing extensive context to your question.

I took a look at your example, and you are using `debug()` before the submenu items are rendered into the DOM. We can utilize `waitForElement` to ensure our submenu items are rendered into the DOM before we use `debug()`:

```diff
  fireEvent.mouseEnter(nav);
+ await waitForElement(() => getByText("Option 9"));
  debug();
```
