### ISSUE TITLE
Some styles (transform, WebkitTransform) are not rendered to the dom

### ISSUE THREAD

**Issue by edi9999** [kentcdodds/react-testing-library#249]
- `react-testing-library` version: 5.4.0
- `react` version: 16.5.2
- `node` version: 8.14.0
- `npm` (or `yarn`) version: 6.5.0

It seems that some special styles are not rendered at all to the document, I don't think it is intended.

### Relevant code or config:

```js
import * as RTL from "react-testing-library";
import React from "react";

it("should render all types of styles", function () {
    const root = RTL.render(<div style={{
        display: 'none',
        WebkitTransform: `translate3d(0px, 0, 0)`,
        transform: `translate3d(0px, 0, 0)`,
    }} className="foobar">Foobar</div>);
    const html =  root.container.innerHTML;
    expect(html).toContain('display');
    expect(html).toContain('translate');
});
```

### What happened:

The innerHTML does not contain translate

```
    Expected string:
      "<div style=\"display: none;\" class=\"foobar\">Foobar</div>"
    To contain value:
      "translate"
```

**Comment by kentcdodds** [comment]
I've actually seen this in the past (not with react-testing-library) and it always confused me. My guess is that it's either something with jsdom or something with React.

In any case this is not something we can fix in react-testing-library. Sorry. Good luck!

**Comment by kentcdodds** [comment]
Interesting 🤔

Could you do a little more [digging](https://kcd.im/dig) please? This is pretty odd.

**Comment by edi9999** [comment]
yes, I just did a little bit of digging.

This is a jsdom version difference.

With jsdom 11.5.1 I have the same issue in my example.

jest wants to keep compatibility for node 4 and node 6 I think, that is why they are stuck on 11.5.1 but it is possible to change the jsdom version with the package : `    "jest-environment-jsdom-thirteen": "^0.0.2",`

**Comment by PhiLhoSoft** [comment]
Thanks for the tip, testing it now. FYI, I will use https://www.npmjs.com/package/jest-environment-jsdom-fourteen
