### ISSUE TITLE
After calling fireEvent.change method. error message not showing in container. (Formik + Yup)

### ISSUE THREAD

**Issue by sagar-gavhane** [kentcdodds/react-testing-library#263]
I have created register form with Formik and Yup. I have to write a test for a case that, if a user enters an invalid email address then a test should ensure that we're showing an appropriate error message to a user. but I haven't get that dom node after `fireEvent.change()` method. I'm pretty new to react-testing-library.

- `react-testing-library` version: 5.4.4
- `react` version: 16.7
- `node` version: v10.15.0
- `npm` (or `yarn`) version: 6.4.1

### Relevant code or config:

```js
fireEvent.change(emailAddress, { target: { value: 'johndoe' } })
await wait(() => {
  // I want to test that email address error should be shown to user.
  expect(emailAddressError).toBeTruthy()
})
```
https://github.com/sagar-gavhane/try-formik-yup/blob/9deb62fb86221bef8daaaade8c9cbf628a8ad3f1/src/containers/Auth/Register/Form.test.js#L44

### What you did:

Trying to test component with react-testing-library.

### What happened:

after change input value with `fireEvent.change()` method. errors message node not rendering to dom.

### Reproduction:

The codebae for this issue can be found here: https://github.com/sagar-gavhane/try-formik-yup

[![Edit try-formik-yup](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/5mxo342844)

**Comment by kentcdodds** [comment]
Rewrite it this way then think about why it works and your old way doesn't:

```js
fireEvent.change(emailAddress, { target: { value: 'johndoe' } })
await wait(() => {
  // I want to test that email address error should be shown to user.
  expect(queryByTestId('emailAddressError')).toBeTruthy()
})
```

This would be even better:

```js
fireEvent.change(emailAddress, { target: { value: 'johndoe' } })
const errorMessage = await waitForElement(() => getByTestId('emailAddressError')))
expect(errorMessage).toBeTruthy()
```

It's all in what the DOM looks like at the time your query runs.
