### ISSUE TITLE
Cannot import extend-expect as per README. 

### ISSUE THREAD

**Issue by antoaravinth** [kentcdodds/react-testing-library#27]
Hello @kentcdodds , 

In the README, we have specified that we could use the extend assertions by importing:

```
import 'react-testing-library/extend-expect'
```

infact this throws an error: 

```
  Cannot find module 'react-testing-library/extend-expect' from 'HelpTest.js'
```

only the below works:

```
import 'react-testing-library/dist/extend-expect'
```

Will debug this and let you know whats happening here.

**Comment by kentcdodds** [comment]
We forgot to add the file to the package.json files list.

**Comment by antoaravinth** [comment]
@kentcdodds Exactly, will raise a PR in sometime.

**Comment by antoaravinth** [comment]
Closing this with reference to : https://github.com/kentcdodds/react-testing-library/pull/28
