### ISSUE TITLE
New Documentation is Not Searchable

### ISSUE THREAD

**Issue by DmacLoyaltyOne** [kentcdodds/react-testing-library#270]
### Problem description:

When going to github page, I am no longer able to search specific api's in documentation.

Before: Go to Github Page -> Ctrl + F -> Search for an API term -> See Usage and Examples
After: Go to Github Page -> Read Docs -> Read Docs -> Ctrl + F 'fireEvent' -> ???

### Suggested solution:

I would suggest adding a search to the Documentation, as I know what I am looking for, but don't know where to find it. 

After searching a little bit, I can see its under Event section, which is pretty logical, but the whole process takes much longer, and to onboard new people to the testing framework will take a while longer since we can no longer see everything on a page, and simply search for it.

Considering that I'm not doing Unit Testing Every single day, I may have to repeat this process every other week or so.

I understand the need to keep the github readme clean, but it takes away the power of search.

**Comment by kentcdodds** [comment]
Hi @DmacLoyaltyOne, thanks for the feedback. You're totally right. We can solve this problem and there's an issue to track this already: https://github.com/alexkrolick/testing-library-docs/issues/3

We just need to get that working. I think it actually should be pretty straightforward.
