### ISSUE TITLE
Support ES5

### ISSUE THREAD

**Issue by chrisprobably** [kentcdodds/react-testing-library#279]
### Describe the feature you'd like:

I'd like react-testing-library to build an ES5 compatible build.  At the moment, I can see there are arrow functions in dist/index.js of version 5.4.4.

### Suggested implementation:

Suggest the same fix as https://github.com/kentcdodds/dom-testing-library/issues/160

**Comment by kentcdodds** [comment]
Hmmm... Where are you running your tests?

**Comment by kentcdodds** [comment]
I'm going to do the same fix as in dom-testing-library, but I'm just curious what environment you're running your tests in that doesn't support arrow functions.

**Comment by chrisprobably** [comment]
Great, thanks :). We're using karma, webpack and Babel. We don't normally transpile dependencies in node_modules.

**Comment by kentcdodds** [comment]
Gotcha. So I take it that you're running some of your tests in IE then?

**Comment by chrisprobably** [comment]
Yes, we run them in IE11.
