### ISSUE TITLE
waitForElementToDisappear

### ISSUE THREAD

**Issue by mastertinner** [kentcdodds/react-testing-library#284]
### Describe the feature you'd like:

I love the `waitForElement` function. However, there are cases where I don't add an element but rather remove existing ones. Is there a similar `waitForElementToDisappear` function or is there an easy way to achieve that using the existing functions?

### Suggested implementation:

```javascript
await waitForElementToDisappear(() => getByText('my button'))
...
```

Currently I'm using `process.nextTick` but that seems like a hack to me:

```
process.nextTick(() => {
    ...
    done()
})
```

**Comment by kentcdodds** [comment]
Could you open this issue in [dom-testing-library](https://github.com/kentcdodds/dom-testing-library/issues)? That's where this work will be done. I'm thinking I'm in favor.
