### ISSUE TITLE
5.5.3 breaks testing for React 15

### ISSUE THREAD

**Issue by alexzherdev** [kentcdodds/react-testing-library#287]
- `react-testing-library` version: 5.5.3
- `react` version: 15.6.2
- `node` version: 10
- `npm` (or `yarn`) version: yarn 1.13

### Relevant code or config:

```js
import React from "react";
import { render } from "react-testing-library";
render(<div />);
```

### What you did:

Just recently installed the library and was trying to write my first tests. Everything was working fine until I updated to 5.5.3.

### What happened:

Trying to render anything in tests results in `ReactDOM.render(): Invalid component element.`

### Reproduction:

https://codesandbox.io/s/lxzrym3p9q

### Problem description:

This seems to be the culprit: https://github.com/kentcdodds/react-testing-library/blob/1d45c5c2ca1281187dc7735ac0e2f12137b157d3/src/act-compat.js#L10
Rendering `null` only works in React 16, not in 15.x.

### Suggested solution:

I'm actually not too sure why that line is necessary in the first place. Why is just calling `ReactDOM.unstable_batchedUpdates` not enough?

**Comment by kentcdodds** [comment]
Ah, yep, that'll do it. The fix is to render `<div />` instead of `null`. Want to make a pull request for that?
