### ISSUE TITLE
Testing useEffect callback

### ISSUE THREAD

**Issue by Andrewmat** [kentcdodds/react-testing-library#289]
### Describe the feature you'd like:

I've had this problem [on a personal project](https://github.com/Andrewmat/hooks/blob/master/src/hooks/useDocumentTitle.test.js) to try and create custom hooks.

The `useEffect` hook accepts a function as argument, and if this function returns another function, React will call it when the component unmounts

```javascript
useEffect(() => {
  subscribe(channel)
  return () => {
    // componentWillUnmount
    unsubscribe(channel)
  }
})
``` 

The testHook API already can test the useEffect call, but I couldn't find a way to test the callback on unmount.

### Suggested implementation:

The `testHook` function renders a wrapper component and already has access to the `unmount` function. My suggestion is to simply return it inside an object.
```jsx
function testHook(callback) {
  const { unmount } = render(<TestHook callback={callback} />)
  return { unmount }
}
```

This is simple to do, and I think it is clear too. Also it can be expand to other important return values when needed.

### Describe alternatives you've considered:

My first thought was to return the unmount function alone

```jsx
function testHook(callback) {
  const { unmount } = render(<TestHook callback={callback} />)
  return unmount
}
```

I did this to mimic the behavior of the `useEffect`. However, it didn't look good to me, as it would get all the usage of `testHook` return.  

### Teachability, Documentation, Adoption, Migration Strategy:

I've took the liberty to create a fork containing my sugestion.
https://github.com/Andrewmat/react-testing-library

Plus [tests](https://github.com/Andrewmat/react-testing-library/blob/master/src/__tests__/test-hook.js) and a [example](https://github.com/Andrewmat/react-testing-library/blob/master/examples/__tests__/react-hooks.js)

I've already tested in [my personal project](https://github.com/Andrewmat/hooks/blob/testing-unmount/src/hooks/useDocumentTitle.test.js) using `yarn link` and it worked.

![captura de tela de 2019-02-08 21-38-14](https://user-images.githubusercontent.com/5133846/52512801-08b80800-2bee-11e9-97b9-e097913188ca.png)

If this feature is considered, I'd be glad to make a pull request of it.

**Comment by kentcdodds** [comment]
Why don't we just return everything?

**Comment by Andrewmat** [comment]
I think it would be an overkill, and since they all control the React element, I assume it *could* encourage some people to make tests basing on the TestHook component instead of the hook.
Although, I see the value of `rerender` to check the deps array of `useEffect`

**Comment by kentcdodds** [comment]
True. Ok, I'm in favor of returning just what's need 👍

**Comment by Andrewmat** [comment]
PR merged, I'm closing this issue
