### ISSUE TITLE
Typings for testHook are incorrect

### ISSUE THREAD

**Issue by carlos-algms** [kentcdodds/react-testing-library#291]
- `react-testing-library` version: 5.6.0

### Relevant code or config:

`node_modules\react-testing-library\typings\index.d.ts`

![image](https://user-images.githubusercontent.com/4634613/52591647-97659880-2e2b-11e9-8cbc-079211c4c064.png)

### Reproduction:
![image](https://user-images.githubusercontent.com/4634613/52591536-566d8400-2e2b-11e9-9cf3-7daaadae0bd2.png)

### Problem description:

It is impossible to run tests using `testHook` with TypeScript due to incorrect typings definitions.

**Comment by alexkrolick** [comment]
Closed by #292

**Comment by carlos-algms** [comment]
Thank you so much for the fast solution.
