### ISSUE TITLE
Doc encouraging user to use `title` instead of `aria-label`

### ISSUE THREAD

**Issue by Grsmto** [kentcdodds/react-testing-library#301]
Hi,

### Problem description:

The documentation gives the [following](https://testing-library.com/docs/guide-which-query#priority) statement: `The title attribute is usually more accessible by screen readers than mouse/visual users`. However [the official W3C WAI tutorial](https://www.w3.org/WAI/tutorials/forms/labels/#using-the-title-attribute) says pretty much the exact opposite:
`[The title attribute] is generally less reliable [than aria-] and not recommended because some screen readers and assistive technologies do not interpret the title attribute as a replacement for the label element, possibly because the title attribute is often used to provide non-essential information.`

### Suggested solution:

From what I understand of the WAI tutorial, the `aria-label` approach is better for accessibility (screen-readers) than the `title` as that one might be ignored. The doc at the moment seems like encouraging the user to use `title` instead of `aria-` which might lead to bad practices.
However I read #16 but I'm not sure to understand what has been agreed on regarding usage of `aria-`  and selectors. As there is a built-in `getByTitle` but no built-in selectors for `aria-` attributes.

Thanks!

**Comment by alexkrolick** [comment]
That statement was meant to reflect this:

The title attribute is not visible on the screen except when hovering, but is read by assistive technology. So selecting by title is less representative of how a sighted user would find elements. Label tags and aria-label are visible on screen and read out by a assistive technology.

**Comment by kentcdodds** [comment]
Moved to https://github.com/alexkrolick/testing-library-docs/issues/38
