### ISSUE TITLE
render() always returning undefined

### ISSUE THREAD

**Issue by Ziv-Barber** [kentcdodds/react-testing-library#312]
- `react-testing-library` version: 6.0.0
- `react` version: 16.8.3
- `node` version: 11.9.0
- `npm` (or `yarn`) version: yarn 1.13.0

### Relevant code or config:

```js
import { render, cleanup } from 'react-testing-library'

(in my test)

const { testedContainer } = render(<div />)

// testedContainer is undefined for anything...
```

### What you did:

const { testedContainer } = render(....)

### What happened:

// testedContainer is undefined for anything...

### Reproduction:

I just added react-testing-library to my project and wrote the code above.

**Comment by undeniablyrob** [comment]
Did you find a solution to this? I'm running into the same thing.
```
react-testing-library version: 6.0.4
react version: 16.8.4
node version: 10.14.1
npm (or yarn) version: yarn 1.15.2

**Comment by alexkrolick** [comment]
"testedContainer" is not something returned by render

```diff
- const { testedContainer } = render(<div />)
+ const { container, getByText } = render(<div />)
```

https://testing-library.com/docs/react-testing-library/api#render
