### ISSUE TITLE
shallow

### ISSUE THREAD

**Issue by lipt0n** [kentcdodds/react-testing-library#314]
hi,
Is it possible to shallow render a component? 
I dont wont to test all of children but just my component. with normal render all of my snapshot will fail if I change some small child component .

**Comment by ZackKnopp** [comment]
See [here](https://kentcdodds.com/blog/why-i-never-use-shallow-rendering). He doesn't support it.

Although for my use case (testing redux connected components that could have redux connected component grandchildren) I didn't want to mock my whole app state just to test that the container would call a function on mount. So, I just gave my container a shallowRender prop and passed that in the test.

**Comment by kentcdodds** [comment]
Yeah, react-testing-library wont support shallow rendering. Mocking is the correct way to go about this.

**Comment by sr-shifu** [comment]
Here is the workaround I found working for my RTL-based tests: https://thesametech.com/snapshot-testing-in-rtl/

**Comment by Filipoliko** [comment]
If you mostly care about how the snapshot looks, you can use [shallow-react-snapshot](https://www.npmjs.com/package/shallow-react-snapshot), which takes the result of the render method of react testing library and transforms the html element output into Enzyme-like shallow structure that can be used with jest snapshots.
