### ISSUE TITLE
Firing touchTap event

### ISSUE THREAD

**Issue by luispuig** [kentcdodds/react-testing-library#320]
I am trying to test `onTouchTap` :

```
<button onTouchTap={() => { console.log('touched')}} >xxx</button>
```

with this code:

```
fireEvent(
    getByText('xxx'),
    new Event('touchTap', {
      bubbles: true,
      cancelable: true
    })
  );
```

The touchTap event is not being fired. I am not sure if it a bug or a library limitation because I didn't find the event at this list: https://github.com/kentcdodds/dom-testing-library/blob/master/src/events.js

Thanks!

**Comment by kentcdodds** [comment]
I wonder if maybe the touchTap event isn't supported in jsdom?

**Comment by bcarroll22** [comment]
`onTouchTap` isn't a browser event, so this library won't be able to support it.

**Comment by luispuig** [comment]
Thanks for the answer!
