### ISSUE TITLE
FAQ: "example-react-transition-group" not found

### ISSUE THREAD

**Issue by bernardobelchior** [kentcdodds/react-testing-library#321]
- `react-testing-library` version: N/A
- `react` version: N/A
- `node` version: N/A
- `npm` (or `yarn`) version: N/A

### Relevant code or config:

N/A

### What you did:

1. Go to [this](https://testing-library.com/docs/react-testing-library/faq) page of the documentation.
2. Click "If I can't use shallow rendering, how do I mock out components in tests?"
3. Click in "[Open full test](https://testing-library.com/docs/react-testing-library/example-react-transition-group) for the full example."

### What happened:

Page not found. [Link](https://testing-library.com/docs/react-testing-library/example-react-transition-group) 
![Screen Shot 2019-03-14 at 10 50 02-fullpage](https://user-images.githubusercontent.com/12778398/54347249-ee3ad980-4646-11e9-8bac-1b45bed0c886.png)

### Reproduction:

See "What you did" section

### Problem description:

It should show the example when clicked.

### Suggested solution:

Reupload the example or fix the link.

**Comment by bernardobelchior** [comment]
Just realized the same happens when clicking on "(see [the Guiding Principles section](https://testing-library.com/docs/react-testing-library/guiding-principles))".

I think the problem may be a dynamic url generator, that is not removing `/react-testing-library` from both links.

**Comment by kentcdodds** [comment]
Hi! Thanks for reporting this.

The correct links are: https://github.com/kentcdodds/react-testing-library/blob/master/examples/__tests__/mock.react-transition-group.js and https://github.com/kentcdodds/react-testing-library/blob/master/examples/__tests__/shallow.react-transition-group.js

Would you like to submit a fix yourself? You can click on "Edit Docs on GitHub" at the bottom of the page and [make a pull request](http://makeapullrequest.com) :)

**Comment by bernardobelchior** [comment]
Thanks! [Just did](https://github.com/alexkrolick/testing-library-docs/pull/48)
