### ISSUE TITLE
Better Docs

### ISSUE THREAD

**Issue by tylerthehaas** [kentcdodds/react-testing-library#323]
### Describe the feature you'd like:

I introduced this at work a few months back and overall everyone loves it. The main complaint that I get from co-workers is that the docs make it hard to find answers when they don't know how to do something. I think the reason most are getting confused is because most of the docs are for dom-testing-library and it is not always clear how those methods map over to react-testing-library. It would be nice to have a docs site specifically for react-testing-library complete with examples of how to use each method specifically with React components.

### Suggested implementation:

Write a site that using git book or some other technology that makes it easy to navigate all the queries and functions available.

**Comment by kentcdodds** [comment]
Thanks for the feedback @tylerthehaas. Could you move this to https://github.com/alexkrolick/testing-library-docs please? We'll discuss it there.
