### ISSUE TITLE
waitForElement not working as expect on latest react version(16.8.6)

### ISSUE THREAD

**Issue by aledustet** [kentcdodds/react-testing-library#347]
- `react-testing-library` version: 6.1.1
- `react` version: 16.8.6
- `node` version: 11.10.1
- `yarn` version: 1.13.0
- `jest-dom` version: 3.1.3

### What you did:

Just run ```yarn create react-app from-scratch --typescript```
Add the ```react-testing-library``` and ```jest-dom``` to the package.json, update the ```App.test.tsx``` with:

```js
import React from 'react';
import {render, waitForElement } from 'react-testing-library'
import 'jest-dom/extend-expect'

test('tests', async () => {
  const { getByTestId } = render(
    <div data-testid='error'>something</div>
  );

  const something = await waitForElement(() => getByTestId('error'))
  expect(something).toHaveTextContent('something')
})

```

### What happened:

<img width="847" alt="Screen Shot 2019-04-05 at 3 36 58 PM" src="https://user-images.githubusercontent.com/2413802/55652141-b132b480-57b8-11e9-954c-c5823de60709.png">

### Reproduction:
[code sandbox](https://codesandbox.io/embed/pj04w2434m)

### Problem description:

The tests pass if I downgrade to:
```json
    "react": "16.8.1",
    "react-dom": "16.8.1",,
    "react-testing-library": "5.5.3",
    "jest-dom": "3.0.0"
```

### Suggested solution:

I'm starting the bisect from the versions to see what might be changed.

**Comment by kentcdodds** [comment]
Yup, this should be fixed in a few minutes :)

**Comment by aledustet** [comment]
wow @kentcdodds 34 seconds 🔥 🙇

**Comment by kentcdodds** [comment]
@allcontributors[bot], please add @aledustet for bug

**Comment by kentcdodds** [comment]
No problem! Thanks for taking the time to report the issue!
