### ISSUE TITLE
import `jest-dom/extend-expect` doesn't work

### ISSUE THREAD

**Issue by ar7casper** [kentcdodds/react-testing-library#351]
- `react-testing-library` version: 6.1.2
- `react` version:  16.8.6
- `node` version: 10.15.3
- `npm` (or `yarn`) version: yarn 1.5.1
- `typescript` version: 3.3.33

### What you did and Problem description:

I'm using TypeScript, in my `jest.config.js` file, I've got 
```js
setupFilesAfterEnv: [ '<rootDir>/src/setup.jest.ts' ]
```

In `setup.jest.ts` I've got - 
```js
import "jest-dom/extend-expect";
import "react-testing-library/cleanup-after-each";
```

Up until a few days ago everything was fine, but now, all of a sudden, `toHaveStyle` & `toHaveAttribute` don't work.
Here's the error I'm getting - `Property 'toHaveStyle' does not exist on type 'Matchers<ChildNode>'`

The really weird part is that on CircleCI it works fine and on other machines it also works. 
I've tested the exact same commits. 

I did `rm -rf node_modules && yarn`, nothing.
I even deleted the entire project and re-cloned, didn't help.

When I log inside the setup file, it does get there. 
I'm really confused 🤔 

In addition, did installs of stuff like typescript / jest / yarn,  everything seems fine.

**Comment by ar7casper** [comment]
Upgrading to TS - 3.4.2 seemed to help, but still weird cause worked before.

**Comment by kentcdodds** [comment]
I'm going to guess that this is a problem with your own TS setup as I'm unable to reproduce. Thanks!
