### ISSUE TITLE
waitForElement causes test to hang indefinitely in codesandbox

### ISSUE THREAD

**Issue by afholderman** [kentcdodds/react-testing-library#357]
- `react-testing-library` version: 5.8.0
- `react` version: 16.8.0
- `node` version: 
- `npm` (or `yarn`) version:

### Relevant code or config:

CodeSandbox repo: https://codesandbox.io/s/8y48jm7rn8

### Problem description:

Attempting to use waitForElement in CodeSandbox causes the test to hang indefinitely. In an actual project the issue presented differently with waitForElement never successfully finding the element.

**Comment by kentcdodds** [comment]
You were calling `waitForElement` with the element. You need to call it with a function: https://codesandbox.io/s/o27kw5oly
