### ISSUE TITLE
Element that has been hidden after waiting is still visible

### ISSUE THREAD

**Issue by bolivier** [kentcdodds/react-testing-library#363]
- `react-testing-library` version: 6.1.2
- `react` version: 16.8.6
- `node` version: 11.13.0
- `yarn` version: 1.15.2

### Relevant code or config:

```js
class Hider extends React.Component {
  state = {
    visible: true
  };
  render() {
    return (
      <div>
        <span>{this.props.text || "hi"}</span>
        <button onClick={() => this.setState({ visible: false })}>hide</button>
        <div>{this.props.children}</div>
      </div>
    );
  }
}
```

```js
class App extends React.Component {
  render() {
    return (
      <div>
        <Hider>
          <span>hello world</span>
        </Hider>
      </div>
    );
  }
}
```

```js
it("should not work properly", async () => {
  const wrapper = render(<App visible={false} />);
  fireEvent.click(wrapper.getByText("hide"));
  await wait(() => {
    expect(wrapper.queryByText("hide")).not.toBeInTheDocument();
  });
});
```

### What you did:

I was writing to test a modal component that hides children by returning null.

### What happened:

Querying the container for the text of the button results in returning the button, even though that button isn't present in the DOM.

The error message is `{"location": null} contains: <button />`

A snapshot of that error: 

[
<img width="577" alt="Screen Shot 2019-04-24 at 2 28 26 PM" src="https://user-images.githubusercontent.com/2995224/56688076-5c8aa700-669d-11e9-8578-727dafc96b34.png">
](url)

### Reproduction:

I created a reproduction of the issue here: https://github.com/bolivier/react-testing-library-reproduction

### Problem description:

Event though the components are not present, they are found and the tests fail

### Suggested solution:

I'm unsure of a solution. I did notice that everything behaves as expected if there's no component nesting. So if the `App` component handles the visibility, then the tests will pass.

**Comment by bcarroll22** [comment]
Very subtle, but your issue is this:

```
expect(wrapper.queryByText("hide")).not.toBeInTheDocument();
```

you're querying for the text "hide" which is the text of the button. the button never goes away. i think what you want is to query by text "hello world" 😉

**Comment by kentcdodds** [comment]
Hi @bolivier,

That code doesn't have any logic around hiding stuff based on the visible state: https://github.com/bolivier/react-testing-library-reproduction/blob/70a3b9ec7c4a741faf5a10c1139388d609c6c087/src/Hider.js#L5

Sure you can set the state, but it doesn't actually hide anything. This doesn't have to do with testing... The feature just doesn't work...

Here's it working: https://codesandbox.io/s/4q6lmnx4lx
