### ISSUE TITLE
Simulate doesnt export method types (TypeScript)

### ISSUE THREAD

**Issue by tsiq-swyx** [kentcdodds/react-testing-library#38]
surprised no one ran into this yet but when you try using Simulate.click, this happens:

```bash
[ts] Cannot invoke an expression whose type lacks a call signature. Type 'void' has no compatible call signatures.
(alias) const Simulate: typeof ReactSimulate
import Simulate
```

currently i'm trying to rewrite index.d.ts as:

```ts
import  * as Utils  from 'react-dom/test-utils';
const { Simulate } = Utils;
const ReactSimulate = Simulate;

export Simulate: typeof ReactSimulate;
```

but this doesnt seem to be valid (i'm not super experienced at TS). anyway figured i'd report this,  as someone else probably has the canonical "typescripty" way of doing this

**Comment by tsiq-swyx** [comment]
hi @mbaranovski i saw you also use typescript - are you able to figure this one out? I have not been able to yet

**Comment by SeanRoberts** [comment]
I'm not seeing this issue with typescript.  Have you installed `@types/react-dom`?

**Comment by mbaranovski** [comment]
@tsiq-swyx it is working for me. Make sure you have version 1.9.3 installed.

**Comment by tsiq-swyx** [comment]
yes I have

"@types/react-dom": "^16.0.3",
"react-testing-library": "^1.9.4",


so i have no idea what is wrong. Im gonna go ahead and close this since it
seems to be my fault.
