### ISSUE TITLE
No extend-expect type definitions

### ISSUE THREAD

**Issue by mbaranovski** [kentcdodds/react-testing-library#40]
* `react-testing-library` version: 1.9.3
* `node` version: 9.2.1

**What you did:**
Created fresh project from CRA + typescript scripts and then wrote a simple test
```javascript
test('renders App without crashing', () => {

  const { queryByTestId } = render(<App/>);

  expect(queryByTestId('app-hoc')).toBeInTheDOM();
});
```

**What happened:**
The test is passing but the project does not build. Throwing this error:

> Property 'toBeInTheDOM' does not exist on type 'Matchers<void>'.

**Problem description:**
Typescript won't allow building project when we are using property which does not exist on some particular type (**Matchers<void>** in this case)

**Suggested solution:**
Extend jest expect typings with a new types definition for methods from extend-expect.js

**Comment by antoaravinth** [comment]
Hello, did you try this : https://github.com/kentcdodds/react-testing-library/blob/master/README.md#custom-jest-matchers-typescript

**Comment by mbaranovski** [comment]
Hi, I've just noticed that in the README file...
It works thanks. I'll close the issue.
