### ISSUE TITLE
CleanUp for `toBeInTheDom` and `toHaveTextContent`

### ISSUE THREAD

**Issue by antoaravinth** [kentcdodds/react-testing-library#45]
Following up the conversation on https://github.com/kentcdodds/react-testing-library/pull/44, looks like we need to do bit of clean up on `toBeInTheDom` and `toHaveTextContent` on the jest extensions. I can pick this up and finish this task.

@gnapse Let me know if you have already picked this up.

**Comment by gnapse** [comment]
I started this in #46, and only after that I saw this.

**Comment by antoaravinth** [comment]
Alright, @gnapse this should be given to this library now : https://github.com/kentcdodds/dom-testing-library :) :) 

@kentcdodds Thats a very cool move. In fact I was thinking, how we could decouple the library, so that one can reuse the DOM queries alone and exactly you had done this! This is awesome.. Cheers! 💯

**Comment by kentcdodds** [comment]
Thanks! Sorry it means that y'all's PRs need to be moved over to the other package. Hopefully it should be pretty straightforward though.

**Comment by antoaravinth** [comment]
@kentcdodds No problem, will move them.. Let us know once you completely decouple the codebase and done with your work.

**Comment by kentcdodds** [comment]
I'm finished actually. react-testing-library has already been updated!

I'm hanging out with the family this weekend so I may not get to your PRs right away.

**Comment by antoaravinth** [comment]
Perfect, will give the PR over there in sometime!
