### ISSUE TITLE
getByTestId vs Others

### ISSUE THREAD

**Issue by nickluger** [kentcdodds/react-testing-library#63]
First: @kentcdodds, thank you for this libray and also for all your eye-opening articles. This helped us move to an integration-tests-first approach and made our test suite far more resilient. 

I have a best practice question regarding this library.

The documentation names `getByTestId` an _escape hatch_, to be used exceptionally, and prefers `getByText` etc. 

However in the article[ "Making your UI tests resilient to change"](https://blog.kentcdodds.com/making-your-ui-tests-resilient-to-change-d37a6ee37269) you show an example by [Kyle Shevlin](https://medium.com/@kyleshevlin), where you disapprove the selection of elements by content. The reason: A single button title change (or total removal of a title, as in the example) would break many tests.

Could you please clarify your opinion on that topic?

Thanks in advance!

**Comment by jigargosar** [comment]
@nickluger 
* In the aforementioned article, I couldn't find an example of the following.

> disapprove the selection of elements by content
> A single button title change would break many tests

* Sorry if I am being too dense.
In the article, I found that selection of an element by className/index was discouraged.

* Also, if a button text (content or label) changes, I want all impacted tests to fail, because that change breaks user expectation.

**Comment by nickluger** [comment]
Hey @jigargosar, thank you for the fast response 😄 

Maybe i misunderstood something!

But It says:

> “What about selecting based on content?”

Then he's citing another author:

> 
> Was given a story to change a word to an icon. Simple change, one line of code.
> Didn't tell me like a BAZILLION tests were tied to that one word

> For people wanting more details, I changed the word "delete" to a trash can icon and broke 62 tests acceptance tests. It took me ~14 minutes to run all of the tests to find the broken ones.

Which is concluded:

> So yeah… Don’t try to select for something that’s not intended for testing…

Which is pointing to a disadvantage of content-based selection, in an article that is mainly arguing in favor of `data-testid`.

Now i'm absolutely with you, and personally prefer breaking tests on changing UI, too. This is the user's perspective & also what this library here recommends. 

Was just wondering about the example cited above.

**Comment by kentcdodds** [comment]
Thanks for asking @nickluger. I've actually changed my tune slightly from the response in the blog post you're referring to. My position is now more like what @jigargosar suggests:

> Also, if a button text (content or label) changes, I want all impacted tests to fail, because that change breaks user expectation.

Taking ~14 minutes to find and fix broken tests isn't a big deal to me, and with the utilities in this library it would probably be even easier to do so. In [the README FAQ](https://github.com/kentcdodds/react-testing-library#faq) under "Which get method should I use?" I talk about this a bit more. It's much more important to me that my tests resemble the way the application is used than my tests don't break when I make meaningful changes :) In fact, I _want_ my tests to break when I make meaningful changes :)

Thanks for askin!

**Comment by nickluger** [comment]
Excellent!, thank you for the recommendation, once again. - This is the way we'll go.
