### ISSUE TITLE
Bug with native checkbox

### ISSUE THREAD

**Issue by braposo** [kentcdodds/react-testing-library#91]
* `react-testing-library` version: 3.1.3
* `react` version: 16.3.2
* `node` version: n/a
* `npm` (or `yarn`) version: n/a

### What you did:

Testing controlled native checkbox

### What happened:

Controlled native checkbox stops working if there are tests.

### Reproduction:

https://codesandbox.io/s/405p15qj80

### Problem description:

This is very strange, but I was testing something in a different project and realised that there's some kind of bug with a controlled native checkbox if there's a test (any test really) with `react-testing-library`. It only happens with the native version, anything else works fine!

This is really strange and I can't find any reason why it's breaking like that. Do you have any clues? Thanks!

**Comment by braposo** [comment]
Ok so I decided to test if it could be codesandbox actually and downloaded the example to run it locally. It seems that locally all works fine so it could be a codesandbox issue after all!

Is there anything you might think can be causing this? I'll probably create an issue in their repo referencing this one, but it seems to be related with `react-testing-library` in some way.

**Comment by kentcdodds** [comment]
Thanks @braposo! Yeah, this is odd. I wont personally be spending any time to figure out what's up and fix this behavior, but if anyone else wants to they can be my guest! Thanks again!

I'll just go ahead and close this as it's not a priority, but people can definitely feel free to work on it and if there's something we can do we can look at a PR for it.
