### ISSUE TITLE
Simulating uploading file

### ISSUE THREAD

**Issue by UnderNotic** [kentcdodds/react-testing-library#93]
Is there a way to simulate or fire event to trigger change event on input that is used for uploading files?

**Comment by gnapse** [comment]
I think it should be possible using [`fireEvent`](https://github.com/kentcdodds/react-testing-library#fireeventnode-htmlelement-event-event).

```javascript
import React from 'react'
import {renderIntoDocument, fireEvent} from 'react-testing-library'

test('some test', () => {
  const {getByLabelText} = renderIntoDocument(
    <div>
      <label htmlFor="avatar">Avatar</label>
      <input id="avatar" type="file" />
    </div>
  )
  const fileInputField = getByLabelText('Avatar')
  const event = {
    target: {
      value: '/not/sure/what/goes/in/here',
    },
  }
  fireEvent.change(fileInputField, event)
  // expect here things that should have happened when the file input changed
})
```

Never tried it myself, and can't try it now, but I'd assume is similar to a regular text input field `change` event. You should pass in the `event` object above something that resembles the relevant parts of the actual event object that would be passed in a real situation in the browser.

**Comment by UnderNotic** [comment]
Hey @gnapse 
I've tried Your approach - I don't get any runtime errors but this is not triggering onChange event on react side. Is that the case also for You?Any ideas why this is happening?

**Comment by kentcdodds** [comment]
Hi! I've done this in a work project and I remember I had to do some slightly odd stuff to make it work. Tomorrow I'll be able to reference what I did and I'll give an example here.

**Comment by kentcdodds** [comment]
Here's what I've got for that test:

```javascript
test('can select an image and upload will make a request to upload it', async () => {
  const { container, getByLabelText, getByText, getByAltText } = render(
    <ProfilePhoto />,
  )
  const file = new File(['(⌐□_□)'], 'chucknorris.png', { type: 'image/png' })
  const imageInput = getByLabelText('choose image')
  Simulate.change(imageInput, { target: { files: [file] } })

  await wait(() => getByAltText('image-preview'))
  const dataURL = getByAltText('image-preview').src
  expect(dataURL).toMatchSnapshot(
    'data url in the image-preview src for this string: "(⌐□_□)"',
  )

  // ensure the form is submittable
  expect(getByText('Upload Image').type).toBe('submit')

  // submit the form
  Simulate.submit(container.querySelector('form'))
  expect(mockClient.request).toHaveBeenCalledTimes(1)
  expect(mockClient.request).toHaveBeenCalledWith(expect.any(String), {
    dataURL,
  })
})
```

**Comment by kentcdodds** [comment]
Because this is neither a bug report or a feature request, I'm going to go ahead and close this. Please feel free to ask questions in the spectrum community: https://spectrum.chat/react-testing-library

**Comment by hoodwink73** [comment]
Heyya @kentcdodds 

I was trying out the method you suggested above. But I had a problem in the actual code handler.

It somewhat looks like this

```javascript
  const handleImageUpload = e => {
    console.log(e.target.files[0]) // undefined while testing
    this.onRequestImageUpload(e.target.files[0]) // this works fine in browser
  }
```

So, I had to do this in test

```javascript
test('<UserAvatar /> | Uploading an image should open a modal', () => {
  const {getByLabelText} = render(<UserAvatar name="Arijit" />)

  const inputEl = getByLabelText('Upload new picture')
  const file = new File(['(⌐□_□)'], 'chucknorris.png', {
    type: 'image/png',
  })

  // i have to do this because `input.files =[file]` is not allowed
  Object.defineProperty(inputEl, 'files', {
    value: [file]
  })

  fireEvent.change(inputEl)

  // check for modal now
})
```

I figured this out from jsdom/jsdom#1272

Can you please confirm this? Can your handler just reference `files[0]` while *testing*.

Again thanks a lot. You are awesome.

**Comment by kentcdodds** [comment]
Hi @hoodwink73, so are you saying what you have there is _working_? Or is it not? Are you just asking if there's a way to get around the `defineProperty` thing? If that's all you're asking, my answer is I don't know, but probably not. I wouldn't worry about it though. Good luck!

**Comment by hoodwink73** [comment]
The `defineProperty` thing is working. And yes, I guess I can live with it. 😊

My question was, did this `Simulate.change(imageInput, { target: { files: [file] } })` work for you?

**Comment by kentcdodds** [comment]
It did work for me. Now `Simulate` is removed though and I haven't had a chance to try the `fireEvent` version on my codebase but I'm pretty sure it'll work the same way.

**Comment by krzystof** [comment]
I followed what's written here, and in my test I do this:
```jsx
const file = new File(['dummy content'], 'example.png', {type: 'image/png'})
const imageInput = getByLabelText('Select an image')
fireEvent.change(imageInput, {target: {files: [file]}})
```
But in my component
```jsx
selectFile = e => {
  // e.target.files[0] is undefined
  this.setState({file: e.target.files[0]})
}
```

Works nicely in the browser though.

**Comment by kentcdodds** [comment]
That's probably the problem. Perhaps you can try:

```javascript
const file = new File(['dummy content'], 'example.png', {type: 'image/png'})
const imageInput = getByLabelText('Select an image')
imageInput.files = [file]
fireEvent.change(imageInput)
```

I haven't updated my implementation to the latest version yet so I haven't tried this. Good luck!

**Comment by krzystof** [comment]
That throws `TypeError: Failed to set the 'files' property on 'HTMLInputElement': The provided value is not of type 'FileList'.`.
From what I have found, `files` is a read only property on an `input` of type `file.
It also look like `FileList` is a read only object that can't be easily created.


I have reverted to version 3 to use `Simulate` for now.

**Comment by hoodwink73** [comment]
Hey, @krzystof 

Try something like this

```
test('<UserAvatar /> | Uploading an image should open a modal', () => {
  const {getByLabelText} = render(<UserAvatar name="Arijit" />)

  const inputEl = getByLabelText('Upload new picture')
  const file = new File(['(⌐□_□)'], 'chucknorris.png', {
    type: 'image/png',
  })

  // i have to do this because `input.files =[file]` is not allowed
  Object.defineProperty(inputEl, 'files', {
    value: [file]
  })

  fireEvent.change(inputEl)

  // check for modal now
})
```

**Comment by kentcdodds** [comment]
Once we find a solid solution we should definitely add it to [the examples](https://codesandbox.io/s/github/kentcdodds/react-testing-library-examples)!

**Comment by hoodwink73** [comment]
Here is a [small example](https://codesandbox.io/s/rl0wj028pp)

**Comment by krzystof** [comment]
Damn! Sorry @hoodwink73, I saw your solution before posting, tried it, but I think I did something wrong...
That works well indeed. Thanks a lot for your help!

**Comment by kentcdodds** [comment]
Sweet! Who would like to make the pull request to add this example to the examples codesandbox/repo?

**Comment by hoodwink73** [comment]
✋ I will

**Comment by Lyonsclay** [comment]
Gots some great advice from this thread, but the `fireEvent.change` didn't work for me so I wanted to share that `fireEvent.drop` worked for me. I am using 'react-dropzone'.

```
describe('Uploader', () => {
  test('uploads file', async () => {
    const rows = ['NAME,ADDRESS,ZIP', 'james,1800 sunny ln,40000', 'ronda,1200 peaches ln,50000']
    const file = new File([rows.join('\n')], 'some.csv')
    const { getByText } = render(<Uploader/>)
    const formElement = getByText('Drop File');
    Object.defineProperty(formElement, 'files', { value: [file] });
    fireEvent.drop(formElement)
    await waitForElement(() => getByText('Street Address'))

    expect(getByText('This target list is ready to go!')).toBeDefined()
  })
})
```

**Comment by prakash874** [comment]
>  I will



> Here is a [small example](https://codesandbox.io/s/rl0wj028pp)

Thank you so much for the example  @hoodwink73

**Comment by mlarcher** [comment]
I ran into the same issue with some code using react-hook-form and the above solutions didn't work out for me. After some time digging into the lib, it appeared that the validator was based on the html input `value` property and not its `files` property. Setting both got me of the hook. 
See https://github.com/react-hook-form/react-hook-form/issues/685 for details.

**Comment by alexvcasillas** [comment]
Hi everyone, just ran into this issue today while developing some code and here's how I've managed to make it work as expected!

```typescript
test('To call function props for uploading & uploaded', async () => {
  const mockUpload = jest.fn(
    (base64: string): Promise<string> => {
      return new Promise((resolve) => resolve(base64))
    }
  )
  const mockOnUpload = jest.fn((): void => {
    // Do nothing
  })

  const { getByTestId } = render(
    <AvatarUpload upload={mockUpload} onUpload={mockOnUpload} />
  )

  const upload = getByTestId('upload')
  const file = new File(['(⌐□_□)'], 'chucknorris.png', { type: 'image/png' })

  // Source: https://github.com/testing-library/react-testing-library/issues/93#issuecomment-403887769
  Object.defineProperty(upload, 'files', {
    value: [file]
  })

  fireEvent.change(upload)

  const preview = await waitForElement(() => getByTestId('preview'))

  expect(mockUpload).toBeCalled()
  expect(mockOnUpload).toBeCalled()
  expect(preview).toBeInTheDocument()
})
```

Hope it works for y'all 👍

**Comment by drekevist** [comment]
Just incase someone was running into the same as me:

If you are using the onInput event handler:
```ts
<input
  type="file"
  accept=".json"
  onInput={handleImportProfile}
/>
```

You also need to trigger an input event, not just change:
```ts
fireEvent.change(inputEl, { target: { files: [file] }})
fireEvent.input(inputEl)
```
or
```ts
Object.defineProperty(inputEl, 'files', { value: [file] })
fireEvent.input(inputEl)
```

**Comment by yayobyte** [comment]
> Here's what I've got for that test:
> 
> ```js
> test('can select an image and upload will make a request to upload it', async () => {
>   const { container, getByLabelText, getByText, getByAltText } = render(
>     <ProfilePhoto />,
>   )
>   const file = new File(['(⌐□_□)'], 'chucknorris.png', { type: 'image/png' })
>   const imageInput = getByLabelText('choose image')
>   Simulate.change(imageInput, { target: { files: [file] } })
> 
>   await wait(() => getByAltText('image-preview'))
>   const dataURL = getByAltText('image-preview').src
>   expect(dataURL).toMatchSnapshot(
>     'data url in the image-preview src for this string: "(⌐□_□)"',
>   )
> 
>   // ensure the form is submittable
>   expect(getByText('Upload Image').type).toBe('submit')
> 
>   // submit the form
>   Simulate.submit(container.querySelector('form'))
>   expect(mockClient.request).toHaveBeenCalledTimes(1)
>   expect(mockClient.request).toHaveBeenCalledWith(expect.any(String), {
>     dataURL,
>   })
> })
> ```

Worked for me!

**Comment by vadimshvetsov** [comment]
Now you can use [`upload` function](https://github.com/testing-library/user-event#uploadelement-file--clickinit-changeinit-) from `@testing-library/user-event`

**Comment by luane-aquino** [comment]
@vadimshvetsov if possible, could you show a very small working example? because I have tried using upload from user-event, but not working. Probably I am missing something.

**Comment by vadimshvetsov** [comment]
@luane-aquino yeah, it may look like this:

```js
import { render, screen } from '@testing-library/react'
import user from '@testing-library/user-event'

test("should upload the file", () => {
  const file = new File(["hello"], "hello.png", { type: "image/png" })
  render(<input type="file" data-testid="element" />)

  const input = screen.getByTestId("element")
  user.upload(input, file)

  expect(input.files[0]).toStrictEqual(file)
  expect(input.files).toHaveLength(1)
})
```

**Comment by luane-aquino** [comment]
Thanks @vadimshvetsov . I had seen this example in the docs. But what I meant was a very simple example that I could download and run on my computer.

**Comment by vadimshvetsov** [comment]
@luane-aquino then you could check [this CodeSandbox example](https://codesandbox.io/s/react-testing-library-demo-v5h0o?file=/src/__tests__/test.js). You may take this example to your github repo and run locally afterwards.

**Comment by NickDebug** [comment]
Hi there, are you able to provide examples on how to initialize click or change events in the third parameter `upload(element, file, [{ clickInit, changeInit }])` please? And what sort of use cases would this help?

And does this conflict with `FireEvent` that has been mentioned above?

**Comment by nemanjam** [comment]
> @luane-aquino yeah, it may look like this:
> 
> ```js
>   const file = new File(["hello"], "hello.png", { type: "image/png" })
> ```

Why does this just give empty file in Jest?

```ts
    console.log
      File {}
```

**Comment by AlexKMarshall** [comment]
> Why does this just give empty file in Jest?
> 
> ```ts
>     console.log
>       File {}
> ```

I realise this is a bit old, but have you tried accessing the file properties? When I've done this, it looks like that in the log, but the file name, file type etc are still all accessible. This is how I have it working in my test:

```javascript
 const mockOnChange = jest.fn();
    const mockFile = new File(['some content'], 'mock-file-name.png', {
      type: 'image/png',
    });

    render(
      <>
        <label htmlFor="file-upload">File Uploader</label>
        <FileUpload id="file-upload" onChange={mockOnChange} />
      </>,
    );
    const nativeInput = screen.getByLabelText(/file uploader/i);

    await userEvent.upload(nativeInput, mockFile);

    expect(mockOnChange).toHaveBeenCalledTimes(1);
    expect(mockOnChange).toHaveBeenCalledWith(
      expect.objectContaining({ type: 'change' }),
      [expect.objectContaining({ name: mockFile.name })],
    );
  });
```

Note my onChange handler here isn't the standard input prop, it's been modified to pass an array of the selected files as a second argument. But the basic principle should be ok.

**Comment by carefree-ladka** [comment]
`
test("upload multiple files", () => {
    const handleFiles = jest.fn();
    const { getByTestId } = renderProvider(
      <>
        <label htmlFor="attachments">Documents</label>
        <input
          type="file"
          data-testid="fileInput"
          onChange={handleFiles}
          accept=".jpg, .jpeg, .pdf"
          multiple={true}
        />
      </>
    );
    const files = [
      new File(["logo"], "logo.jpeg", { type: "image/jpeg" }),
      new File(["background"], "background.jpg", { type: "image/jpg" }),
      new File(["resume"], "resume.pdf", { type: "application/pdf" }),
    ];

    const inputField = getByTestId("fileInput");
    fireEvent.change(inputField, { target: { files: [...files] } });

    expect(handleFiles).toHaveBeenCalledTimes(1);
    expect(inputField.files).toHaveLength(3);
    expect(inputField.files[0]).toStrictEqual(files[0]);
    expect(inputField.files[1]).toStrictEqual(files[1]);

    expect(inputField.files[0].name).toBe("logo.jpeg");
    expect(inputField.files[1].name).toBe("background.jpg");
    expect(inputField.files[2].name).toBe("resume.pdf");

    expect(inputField.files[0].type).toBe("image/jpeg");
    expect(inputField.files[1].type).toBe("image/jpg");
    expect(inputField.files[2].type).toBe("application/pdf");
  });
});
`
So I had the doubt of testing my upload component with _multiple={true}_. Unfortunately **userEvent.upload()** didn't work . I wrote this way and it just worked fine for multiple files. Hope it helps others 💯

**Comment by Neurrone** [comment]
I''m noticing that although the name and type properties are defined in the `File` objects when read from event handlers, methods for retrieving the contents of the file such as `.text()` all fail with an error indicating that it isn't a function. It seems methods to actually retrieve the file contents isn't implemented.

I discovered this while simulating uploading a .csv in a component that parses the csv and uses that to change its state.

**Comment by Neurrone** [comment]
Related: https://github.com/jsdom/jsdom/issues/2555

**Comment by yasin-shaikh** [comment]
how can we do with api call  below is my function

**Comment by hqkwao** [comment]
Why not also mention also that you can't  work with an actual file❓😔
I'm asking this because when you are doing interaction test in Storybook it is impossible to use this approach and at the moment there's no documented approach to achieve this.
